Small fixes to Dockerfile
openmc-dev/openmc pull request #1664
Opened 2020-09-17 20:24 UTC by paulromano

This PR has a few small changes to our Dockerfile to ensure it still works:
- Remove `FC` environment variable, which is not needed
- Make Debian frontend non-interactive to avoid prompt asking for timezone
- Explicitly put `--recurse-submodules` on the `git clone` command

2020-09-18 04:23 UTC, AI-Pranto requested changes

2020-09-18 04:23 UTC, AI-Pranto commented on Dockerfile
> +    OPENMC_ENDF_DATA=/root/endf-b-vii.1 \
```suggestion
    OPENMC_ENDF_DATA=$HOME/endf-b-vii.1 \
```
We extract tar archive to  `tar -C $HOME -xJ`.

2020-09-18 04:23 UTC, AI-Pranto commented on Dockerfile
>      OPENMC_CROSS_SECTIONS=/root/nndc_hdf5/cross_sections.xml \
```suggestion
    OPENMC_CROSS_SECTIONS=$HOME/nndc_hdf5/cross_sections.xml \
```
Same we extract tar archive to `tar -C $HOME -xJ`

2020-09-18 04:25 UTC, AI-Pranto commented
@paulromano, Do we really need `ENV CC=/usr/bin/mpicc` this PATH variable?

2020-09-18 04:41 UTC, AI-Pranto commented
@paulromano For `ubuntu 20.04` default python is `python 3.8` and also we have `pip3`. So we can replace
```
apt-get install -y python3-pip && \
```
with 
```
RUN apt-get install -y python-is-python3
RUN ln -s /usr/bin/pip3 /usr/bin/pip
```
It's annoying to type `python3` which we can solve by `python-is-python3`.

2020-09-28 19:49 UTC, paulromano commented
> @paulromano, Do we really need `ENV CC=/usr/bin/mpicc` this PATH variable?

Probably not actually. Only the C++ compiler is used for compiling code that uses MPI, so we could probably get away with just the `CXX` variable, but it doesn't hurt to set `CC` as well.

2020-09-28 19:58 UTC, paulromano commented
@AI-Pranto Thanks for the suggestion about `python-is-python3`. I'll go ahead and add that in. Regarding pip, it looks like in the soon-to-be-released Ubuntu 20.10, `python3-pip` [will install `pip`](https://askubuntu.com/questions/320996/how-to-make-python-program-command-execute-python-3#comment2131288_1031733).

2020-09-28 20:15 UTC, paulromano commented
@AI-Pranto It looks like using `$HOME` actually doesn't work in `ENV` commands (it just evaluates to nothing), which is probably why `/root` had been used in the first place. I'm going to revert those changes.

2020-09-29 01:43 UTC, AI-Pranto commented
`$HOME` in docker actually points to the `\root` directory. My bad! @paulromano. 

LGTM @paulromano I have tested this on Docker and everything's fine.

2020-10-01 06:23 UTC, wbinventor approved these changes

2020-10-01 07:09 UTC, wbinventor commented
Just tried this out in Docker for Windows and it works great!

2020-10-01 22:17 UTC, pshriwise approved these changes
I just tried this out as well and everything seems shipshape. Thanks @paulromano!

2020-10-01 22:17 UTC, merged