Fixed erroneous normal distro sampling
openmc-dev/openmc pull request #1670
Opened 2020-09-28 08:00 UTC by makeclean

Previous normal distribution was just flat out wrong. In my opinion we should shift to - https://en.cppreference.com/w/cpp/numeric/random/normal_distribution for this, but its easy to change - this current method obviously uses prn() which is convenient and fits nicely alongside the other sampling techniques. 

![Screenshot from 2020-09-22 14-29-00](https://user-images.githubusercontent.com/2439754/94405747-e8ddab00-0168-11eb-96e7-13f2ce59539f.png)

Attached is an example of the guassian sampling from this implmentation and another independent gaussian sample, and a gaussian distribution with the same mean and std dev.

I would like an actual unit test on this, but currently none of the sample functions are callable from the python API - should this be done in the longer term too?

2020-09-30 17:05 UTC, gridley commented
Wow, good catch. I was curious to see how wrong the old one was... quite a bit!!

![2020-09-30-130443_1031x983_scrot](https://user-images.githubusercontent.com/18088906/94716907-9396ca80-031d-11eb-94a2-01fbbc1904cd.png)

2020-10-05 12:30 UTC, paulromano requested changes
Thanks for the fix @makeclean!

2020-10-05 12:30 UTC, paulromano commented on src/math_functions.cpp
> +  return mean + standard_deviation*z*v1;
Not a fan of the recursion. How about the following:
```suggestion
  // Sample a normal variate using Marsaglia's polar method
  double x, y, r2;
  do {
    x = 2 * prn(seed) - 1.;
    y = 2 * prn(seed) - 1.;
    r2 = x*x + y*y;
  } while (r2 > 1 || r2 == 0);
  double z = x * std::sqrt(-2.0 * std::log(r2)/r2);
  return mean + standard_deviation*z;
```

2020-10-05 12:30 UTC, paulromano commented on src/math_functions.cpp
> -  // 8 in https://permalink.lanl.gov/object/tr?what=info:lanl-repo/lareport/LA-05411-MS
I would still leave a comment pointing to a source for the equation used

2020-10-05 12:30 UTC, paulromano commented on tests/unit_tests/test_math.py
> +    del samples
Python will clean up garbage itself
```suggestion
```

2020-10-05 12:30 UTC, paulromano commented on tests/unit_tests/test_math.py
> +    from scipy.stats import shapiro
Put this up at the top of the file

2020-10-05 12:30 UTC, paulromano commented on tests/unit_tests/test_math.py
> +        prn_seed = prn_seed + 1
If we're confident this test will always pass, wouldn't it be ok to just use seeds that are not pre-determined? i.e., you'll get a different set of samples each time the test runs, but they should always be normally distributed

2020-10-05 12:30 UTC, paulromano commented on tests/unit_tests/test_math.py
> +    assert stat > 0.97
Shouldn't the test compare the p value as opposed to the test statistic?

2020-12-23 18:42 UTC, pshriwise commented
This was wrapped up by @paulromano in #1739. Thanks for taking it this far @makeclean! Closing...

2020-12-23 18:42 UTC, closed without merging