Merge RegularMesh and RectilinearMesh features into base class
openmc-dev/openmc pull request #1696
Opened 2020-10-15 23:30 UTC by aprilnovak

This MR puts as much of the functionality common to the `RegularMesh` and `RectilinearMesh` classes into their shared base class, `StructuredMesh`, with the addition of a few minor member access functions that capture the (small) differences that existed between these classes in the first place.

Functionality that has been moved up to the `StructuredMesh` class:

- `intersects`
- `bins_crossed`
- various query methods, `get_bin_from_indices`, `get_indices`, `get_indices_from_bin1`, `n_bins`, `n_surface_bins`, `get_bin`

New abstract methods in `StructuredMesh` (overridden by `RegularMesh` and `RectilinearMesh` that made this refactoring possible):

- `get_index_in_direction`: get mesh index for given Position in a particular coordinate direction
- `positive_grid_boundary`: coordinate of next grid boundary for positive direction
- `negative_grid_boundary`: coordinate of next grid boundary for negative direction

The only method that can probably still be refactored that I didn't touch is the `surface_bins_crossed` method, because there are non-trivial differences between the two implementations. Will do this in a future PR!

This deletes about 250 lines from `src/mesh.cpp` without any loss of functionality.

2020-10-15 23:34 UTC, aprilnovak commented
Before I refactor the `surface_bins_crossed` method, would someone be able to explain to me what `n_surface_bins` really represents? For a 2x2 mesh in 2-D, OpenMC determines that there are 32 surface bins, but I would have thought the number would be 12, or possibly 16.

My interpretation of surface bin numberings:


```
      7         8
  --------------------
  |         |        |
1 |        9|        | 6
  |   11    |  12    |
  --------------------
  |         |        |
2 |       10|        | 5
  |   3     |   4    |
 --------------------
```

2020-10-16 19:46 UTC, paulromano approved these changes
Looks great to me. PRs with a net reduction of lines-of-code are always a win in my book!

@pshriwise @smharper I'd like it if one of you can review this as well since you guys have been more involved with the mesh classes.

2020-10-19 00:23 UTC, smharper requested changes
Nice PR! It's good to see all that redundancy removed.

I have a small change request though related to performance. Here `StructuredMesh::bins_crossed` uses `std::vector`s for the arrays `ijk0`, `ijk1`, and `d`. I think it's better to use C-style arrays for those variables. If I understand correctly, the `std::vector` data will get allocated on the heap, but a C-style array will live on the stack. On my computer, it looks like it makes for a 10% performance difference on the pincell example.

I think we ran into this issue once before when we first switched from Fortran to C++, but it looks like we accidentally moved `RegularMesh::bins_crossed` variables back to `std::vector`s. Maybe we should also stick some comments on the relevant code about the performance issue so we don't accidentally go back to `std::vector` again.

2020-10-19 00:30 UTC, smharper commented
For the `n_surface_bins` question: with current tallies we'll compute the partial current on each surface of each mesh bin. So in 2D, we'll tally 2 values (incoming and outgoing current) for each of the 4 sides. With 4 mesh cells that's 4*4*2 = 32.

This does lead to a lot of redundancy; the outgoing current on the right side of cell 1 is equal to the incoming current on the left side of cell 2. I think we'd all be cool with removing that redundancy, but it's a big project to implement all the right indexing stuff.

2020-10-19 13:19 UTC, paulromano commented
@smharper I think part of the reason we ended up with `std::vector`s inside of `bins_crossed` is that `int ijk0[n]` where `n` is determined at runtime is a variable-length array, which is not standard C++. gcc/clang don't complain about it, but some compilers do (e.g., MS Visual Studio). However, since know the upper-bound, they could be declared as `int ijk0[3]`.

2020-10-19 14:01 UTC, smharper commented
@paulromano, oh that's right! It's kind of surprising those arrays aren't part of the standard, but alas.

2020-10-19 21:26 UTC, aprilnovak commented
Thanks @smharper! I changed `bins_crossed` so that now all `std::vector`s are length-3 arrays. I didn't make similar changes in `surface_bins_crossed` because I didn't consolidate those methods in this PR because they were non-trivially different for `RegularMesh` and `RectilinearMesh`. When I do consolidate them, I will make sure to use the arrays!

2020-10-20 02:15 UTC, gridley commented
Whoa... such a strange coincidence you all are working on this. I was just now profiling the CUDA-based OpenMC and found the allocation and deallocation of these `std::vector`s in this part of the code to be really killing my particle tracking rate, since they were reserving then freeing GPU memory. Please let me know if I can help in any way to hasten getting this merged. :smile:

2020-10-20 03:16 UTC, smharper approved these changes
Looks good to me!

2020-10-20 03:16 UTC, merged

2020-10-20 03:19 UTC, smharper commented
As a side note @gridley, I often find use collision-estimated tallies for my applications because the software performance boost (due to not using the complex `bins_crossed` function) makes up for the potential drop in estimator efficiency.