changing element to element.title to catch lowercase entries
openmc-dev/openmc pull request #1839
Opened 2021-05-17 17:09 UTC by Shimwell

A new OpenMC user messaged me the other day as they were having some trouble making Materials

They had accidentally been adding elements in the following way for a few hours and couldn't figure out what was wrong as there was no error or warning returned when the materials were made they had assumed the materials had been made correctly.

Situation 1 - no errors raised when material is made - resulting material has no nuclides
```python
import openmc
my_mat = openmc.Material()
my_mat.add_element('o', 2)
my_mat.add_element('c', 1)
```

Situation 2 - no errors raised when material is made - resulting material has only one of two nuclides
```python
import openmc
my_mat = openmc.Material()
my_mat.add_element('O', 2)
my_mat.add_element('c', 1)
```

I notice that if the user enters "Oxygen" or "oxygen" or even "OXYGen" then all options are accepted and result in oxygen being added. Perhaps we should do the same for symbols.

This tiny PR adds a ```.title()``` to the elements symbol so that it will always have the upper case first letter and lower case 2nd letter.

Alternatively if this idea is not popular then perhaps I can get the Add_element method to raise an error if the element symbol is not in the ```openmc.data.ELEMENT_SYMBOLS``` dictionary?

2021-05-18 03:05 UTC, paulromano requested changes
Good observation here -- it would be nice to either allow this or give the user some indication they are doing something wrong. I think perhaps we should take the same approach that is used in `Material.add_nuclide` where a warning is displayed if the name looks unusual, e.g.:
```python
>>> m = openmc.Material()
>>> m.add_nuclide('u235', 1.0)
/home/romano/openmc/openmc/material.py:386: UserWarning: 'u235' does not appear to be a nuclide name in GND format
  warnings.warn(str(e))
```

2021-05-19 12:36 UTC, Shimwell commented
I've added checks for incorrect usage of uppercase and lowercase in the element symbol and a check to see if the element symbol provided is in the list of elements in openmc.data.

Also put in a few tiny unit tests to check it works.

2021-05-27 12:54 UTC, paulromano approved these changes

2021-05-27 12:54 UTC, merged

2021-05-27 12:54 UTC, paulromano commented
Thanks @Shimwell!

2021-05-27 12:55 UTC, Shimwell commented
Super thanks for merging this little addition much appreciated