Remove Jupyter notebooks from documentation
openmc-dev/openmc pull request #1857
Opened 2021-07-15 15:08 UTC by paulromano

We now have our Jupyter notebooks maintained in a [separate repository](https://github.com/openmc-dev/openmc-notebooks) along with a [wiki page](https://github.com/openmc-dev/openmc/wiki/Example-Jupyter-Notebooks) that links to those notebooks as well as other user-contributed notebooks. This PR removes the example notebooks from our main docs on docs.openmc.org and replaces them with a link to the wiki page, which will be easier to maintain going forward.

2021-07-22 12:44 UTC, nelsonag commented on .gitignore
> -# xml-fortran reader
The last of an era..

2021-07-22 13:14 UTC, nelsonag requested changes
Good change @paulromano 
One request from building this:
- source/pythonapi/index.rst still has a reference to examples in the first paragraph :ref:"examples") (single quotes changed to double to avoid code blocks). Might as well make that a hyperlink to the new wiki location.

2021-07-22 14:33 UTC, paulromano commented
Good call @nelsonag. Just made that update

2021-07-27 18:52 UTC, nelsonag approved these changes
Looks good to me, thanks @paulromano!

2021-07-27 18:52 UTC, merged