Addition of C-API methods to set/get a Cell's rotation and translation
openmc-dev/openmc pull request #1859
Opened 2021-07-28 10:40 UTC by nelsonag

As stated, this simple PR gives a user C-API access to a Cell's rotation and translation attributes. This can be useful for performing criticality searches as discussed in #1654 as this allows control device movement without going back through XML and re-initialization.

Unit tests are included in ``test_lib.py``.

2021-07-28 20:51 UTC, paulromano requested changes
Nice idea @nelsonag!

2021-07-30 16:42 UTC, nelsonag commented
All fixed @paulromano thanks for the review!

2021-08-02 18:39 UTC, paulromano approved these changes

2021-08-02 18:39 UTC, merged

2021-08-02 18:39 UTC, paulromano commented
Thanks @nelsonag!