Ensure particles lost during event_calculate_xs are terminated
openmc-dev/openmc pull request #1911
Opened 2021-11-19 21:41 UTC by paulromano

A user recently [ran into a problem](https://openmc.discourse.group/t/warning-could-not-find-the-cell-containing-particle-505877/1493) where a lost particle results in the code segfaulting. After some investigation, I realized the reason this happens is because the particle gets marked as lost during `Particle::event_calculate_xs`:
https://github.com/openmc-dev/openmc/blob/02239256f673ea1b0c73501ae1f2feac4a17d129/src/particle.cpp#L106-L110

Even though it's marked as lost, there is no check right now between `event_calculate_xs` and `event_advance` that a particle is actually still alive, and so we end up accessing memory that we shouldn't. The quick fix is to just add a check for `p.alive()` in between these events. There is a deeper geometry problem at hand that results in the particle getting lost in the first place, but that will take a bit more work to resolve. In the meantime, we should at least ensure that lost particles don't result in segfaults, which is the goal of this PR.

2021-11-20 05:22 UTC, gridley commented
It blows my mind that we can't find the cell there. This find cell statement only gets called at the beginning of a particle history and after revival from a secondary. Since the IndependentSource does rejection sampling until the sampled location results in a successful find_cell call, we know that this is getting triggered after revival from a secondary. Maybe?

Anyway, LGTM.

2021-11-20 05:23 UTC, gridley approved these changes

2021-11-20 16:57 UTC, gridley commented
OK, so, I tried running this, and it still seems to error out:

```
HDF5-DIAG: Error detected in HDF5 (1.12.1) thread 0:
  #000: H5F.c line 532 in H5Fcreate(): unable to create file
    major: File accessibility
    minor: Unable to open file
  #001: H5VLcallback.c line 3282 in H5VL_file_create(): file create failed
    major: Virtual Object Layer
    minor: Unable to create file
  #002: H5VLcallback.c line 3248 in H5VL__file_create(): file create failed
    major: Virtual Object Layer
    minor: Unable to create file
  #003: H5VLnative_file.c line 63 in H5VL__native_file_create(): unable to create file
    major: File accessibility
    minor: Unable to open file
  #004: H5Fint.c line 1839 in H5F_open(): unable to open file: name = 'results/particle_25_526678.h5', tent_flags = 13
    major: File accessibility
    minor: Unable to open file
  #005: H5FD.c line 723 in H5FD_open(): open failed
    major: Virtual File Layer
    minor: Unable to initialize object
  #006: H5FDsec2.c line 352 in H5FD__sec2_open(): unable to open file: name = 'results/particle_25_526678.h5', errno = 2, error message = 'No such file or directory', flags = 13, o_flags = 242
    major: File accessibility
    minor: Unable to open file
 ERROR: Failed to open HDF5 file with mode 'w': results/particle_25_526678.h5
```

After I made a directory called "results" for the restart data to be written to, it worked great.

2021-11-20 16:59 UTC, gridley requested changes
Definitely should fix the issue with a "results" directory not being created before merging this.

2021-11-20 17:14 UTC, gridley commented
Now here's something weirder. When I get the restart h5 files, and try to re-run them from the h5 specs, OpenMC is doing the find_cell call just fine! What on Earth... This makes it far harder to debug.

2021-11-22 04:17 UTC, pshriwise commented
> Now here's something weirder. When I get the restart h5 files, and try to re-run them from the h5 specs, OpenMC is doing the find_cell call just fine! What on Earth... This makes it far harder to debug.

I noticed this too. Just created an issue for what's going on there, #1912.

2021-11-22 05:03 UTC, pshriwise commented
> OK, so, I tried running this, and it still seems to error out:
> 
> ```
> HDF5-DIAG: Error detected in HDF5 (1.12.1) thread 0:
>   #000: H5F.c line 532 in H5Fcreate(): unable to create file
>     major: File accessibility
>     minor: Unable to open file
>   #001: H5VLcallback.c line 3282 in H5VL_file_create(): file create failed
>     major: Virtual Object Layer
>     minor: Unable to create file
>   #002: H5VLcallback.c line 3248 in H5VL__file_create(): file create failed
>     major: Virtual Object Layer
>     minor: Unable to create file
>   #003: H5VLnative_file.c line 63 in H5VL__native_file_create(): unable to create file
>     major: File accessibility
>     minor: Unable to open file
>   #004: H5Fint.c line 1839 in H5F_open(): unable to open file: name = 'results/particle_25_526678.h5', tent_flags = 13
>     major: File accessibility
>     minor: Unable to open file
>   #005: H5FD.c line 723 in H5FD_open(): open failed
>     major: Virtual File Layer
>     minor: Unable to initialize object
>   #006: H5FDsec2.c line 352 in H5FD__sec2_open(): unable to open file: name = 'results/particle_25_526678.h5', errno = 2, error message = 'No such file or directory', flags = 13, o_flags = 242
>     major: File accessibility
>     minor: Unable to open file
>  ERROR: Failed to open HDF5 file with mode 'w': results/particle_25_526678.h5
> ```
> 
> After I made a directory called "results" for the restart data to be written to, it worked great.

I'm guessing the `<path>` element was set in the `settings.xml`? In that case, openmc does expect the directory to exist ahead of time (docs link: https://docs.openmc.org/en/latest/io_formats/settings.html#output-element).

2021-11-22 05:06 UTC, pshriwise approved these changes
I just restarted CI b/c `test_tally_aggregation` failed. Assuming the new run completes successfully, I'm good with this. Thanks @paulromano!

2021-11-22 13:22 UTC, paulromano commented
@gridley. Yes, the geometry bug that leads to this behavior is a little mind blowing. What happens is that we sample a distance to collision which is almost exactly the same as the distance to the outer boundary (but ever so slightly less), so the particle has a collision right near the boundary. Then, the next time we calculate the distance to boundary, the fact that the particle's currently position is effectively coincident with the surface means that we don't check that intersection point. Consequently, the distance to boundary ends up being infinite (since the particle is facing away from the rest of the geometry) and eventually the particle has a collision outside the model and produces a secondary there. When the secondary becomes active, that's where find cell fails and produces the segfault this PR is meant to fix. However, we also need some sort of robust solution for the underlying geometry issue so that particles don't get lost in the first place. @pshriwise and I haven't come up with any good solutions so far.

I've also noticed the particle restart issue and that should hopefully be an easy fix. We can discuss that one further in #1912.

2021-11-22 15:13 UTC, paulromano commented
@pshriwise I just pushed another commit that should fix #1912.

2021-11-22 17:11 UTC, pshriwise approved these changes
Looks good! Nice to have that restart capability back. Thanks for the additional fix. On to addressing the geometry problem...

2021-11-22 17:11 UTC, pshriwise commented on src/particle_restart.cpp
> +  case RunMode::FIXED_SOURCE:
I'm glad this is the approach you settled on as it simplifies the code (to me) and is agnostic to the run mode.

2021-11-23 17:21 UTC, pshriwise commented
Any further comments or suggestions @gridley?

2021-11-23 21:04 UTC, gridley approved these changes
Thanks for pinging me @pshriwise. yeah, looks great!!

2021-11-23 21:07 UTC, merged