writing files to output folder
openmc-dev/openmc pull request #1998
Opened 2022-03-10 21:04 UTC by shimwell

As discussed in #1996 this PR is an attempt to allow the summary.h5 and tallies.out to be written to the output folder (if specified in the settings object) along with the other output files (statepoint..h5 and tracks....h5)

2022-03-10 21:08 UTC, shimwell commented on src/output.cpp
> +  filename = fmt::format("{}tallies.out", settings::path_output, w);
```suggestion
  filename = fmt::format("{}tallies.out", settings::path_output);
```

2022-03-10 21:08 UTC, shimwell commented on src/summary.cpp
> +  filename = fmt::format("{}summary.h5", settings::path_output, w);
```suggestion
  filename = fmt::format("{}summary.h5", settings::path_output);
```

2022-03-11 15:28 UTC, paulromano requested changes

2022-03-11 15:28 UTC, paulromano commented on src/output.cpp
> +  filename = fmt::format("{}tallies.out", settings::path_output);
```suggestion
  std::string filename = fmt::format("{}tallies.out", settings::path_output);
```

2022-03-11 15:28 UTC, paulromano commented on src/summary.cpp
> +  filename = fmt::format("{}summary.h5", settings::path_output);
```suggestion
  std::string filename = fmt::format("{}summary.h5", settings::path_output);
```

2022-03-11 20:50 UTC, paulromano approved these changes
Simple enough change -- thanks for another contribution @shimwell!

2022-03-11 20:50 UTC, merged