Update Cmake to allow third-party libraries
openmc-dev/openmc pull request #2006
Opened 2022-03-16 20:50 UTC by kkiesling

This addresses #1779. CMake will now search for existing installations of xtensor, xtl, and gsl-lite and use those instead. If not found, it'll use the vendored submodules.

2022-03-17 04:21 UTC, paulromano requested changes
Thanks @kkiesling and congrats on your first PR here! :tada: Just a few comments regarding how we handle xtl

2022-03-17 04:21 UTC, paulromano commented on CMakeLists.txt
> +endif()
Since xtl is a transitive dependency (OpenMC → xtensor → xtl) I think we should be able to omit the check for xtl altogether:
```suggestion
```

2022-03-17 04:21 UTC, paulromano commented on CMakeLists.txt
> +endif()
I think it's safe to assume that if xtensor is not found, we should use the submodules for both xtensor and xtl:
```suggestion
if (NOT xtensor_FOUND)
  add_subdirectory(vendor/xtl)
  set(xtl_DIR ${CMAKE_CURRENT_BINARY_DIR}/vendor/xtl)
  add_subdirectory(vendor/xtensor)
endif()
```

2022-03-17 21:07 UTC, kkiesling commented
One last change and hopefully this makes it work- I updated the xtl and xtensor versions on the CI build script for vectfit to be the versions that are vendored. This new find_package change was finding the versions installed with vectfit, but they were too old and didn't have some of the functions currently used by openmc.

2022-03-18 03:13 UTC, paulromano approved these changes
Looks good! Thanks for working through the strange build issues :smile: Will merge tomorrow morning if there's no more feedback

2022-03-18 15:45 UTC, merged