Use `openmc` executable when calling Universe.plot
openmc-dev/openmc pull request #2019
Opened 2022-03-31 20:00 UTC by paulromano

Right now, the `Universe.plot` method generates a plot by looping over all the pixels and calling `Universe.find(...)`. That is, all the logic happens at the Python level, which can be very slow if the geometry is complex or the resolution is high. This pull request changes `Universe.plot` so that it calls `openmc -p` under the hood to generate an image and then loads it in. While working on this, I also noticed that the `plot_inline` function and `Plot.to_ipython_image` method don't work when a different working directory is passed -- that has been fixed here. Finally, I added a one-line fix for #2017.

2022-04-01 15:37 UTC, paulromano commented
One more small change I added here -- `Model.export_to_xml` now has a `remove_surfs` argument that gets passed on to `Geometry.export_to_xml`

2022-04-07 15:10 UTC, pshriwise requested changes
A couple of very small items and then this looks good to me @paulromano! Thanks for taking care of that decay value too.

2022-04-07 18:23 UTC, paulromano commented on openmc/model/model.py
> +            exporting
I added punctuation on the ones I added here, but yes we probably ought to have a separate PR addressing this throughout

2022-04-07 18:33 UTC, pshriwise approved these changes
Thanks @paulromano! Will merge once tests pass!

2022-04-07 22:21 UTC, merged