Kalbach-Mann slope calculation for ENDF files
openmc-dev/openmc pull request #2022
Opened 2022-04-02 06:55 UTC by JoffreyDorville

Hi everyone,

This PR enables the calculation of the slope parameter of a Kalbach-Mann distribution when it is not provided in an ENDF file. This calculation is already used in NJOY2016 to produce ACE files from ENDF files, and described in the ENDF-6 Formats Manual.

In this PR, the calculation is only valid if the projectile is a neutron. To check if the projectile is a neutron, the projectile mass is retrieved from the ENDF evaluation and compared to 1. Having access to the ZA identifier (Zx1000 +A) would be better, but I have not been able to find a way to retrieve it.

The calculation is performed as defined in the ENDF-6 Manual, BNL-203218-2018-INRE, Revision 215, File 6 description for LAW=1 and LANG=2. One exception to this, is that the entrance and emission channel energies are not calculated with the AWR number, but approximated with the number of mass instead.

The development is tested against HDF5 files and NJOY calculations for 3 isotopes, MT=5, and neutron as projectile and emitted particle. Because ENDF files can not be used directly to produce HDF5 files for the moment, the test against HDF5 files makes sense. However, if this limitation is lifted, the test is no longer valid as we could potentially end up comparing the same values. In my opinion, the test against NJOY is sufficient, but I wanted to provide both for discussion.

The AtomicRepresentation class has been developed to simplify the manipulation of isotopes from their ZA identifier. For the moment, this class is stored in the kalbach_mann module which does not seem ideal, but it could easily be stored in its own module.

Additionally, a new “smoothing” parameter has been added to the make_ace function. The objective is to be able to remove the smoothing option in the ACER call, so that distributions from ENDF and ACE files share the same energy grid and can be compared directly.

2022-04-07 20:40 UTC, paulromano requested changes
@JoffreyDorville Thanks for the PR. If it's OK with you, I'm going to do some refactoring on this branch and send a pull request to your fork. I'm off on vacation tomorrow through 4/15, so unfortunately it's going to have to wait a bit. Sorry about that!

2022-04-08 17:37 UTC, JoffreyDorville commented
@paulromano Sure, I also think that some refactoring is needed before being completely ready for merging. Thank you for your help on this, and enjoy your vacation!

2022-07-27 18:47 UTC, paulromano requested changes
Just a few trivial changes and then this is good to go. Thanks @JoffreyDorville!

2022-07-27 18:47 UTC, paulromano commented on openmc/data/njoy.py
> +1 1 {ismoothing}/
Just to be consistent with the NJOY manual
```suggestion
1 1 {ismooth}/
```

2022-07-27 18:47 UTC, paulromano commented on openmc/data/njoy.py
> +        ismoothing = int(smoothing)
```suggestion
        ismooth = int(smoothing)
```

2022-07-27 18:47 UTC, paulromano commented on openmc/data/reaction.py
> +    IOError:
```suggestion
    IOError
```

2022-08-05 16:50 UTC, paulromano approved these changes

2022-08-05 16:51 UTC, merged

2022-08-05 16:51 UTC, paulromano commented
Thanks again @JoffreyDorville!