added scale 44 group structure
openmc-dev/openmc pull request #2044
Opened 2022-04-27 14:49 UTC by shimwell

This PR is an attempt to add SCALE-44 to the collection of energy group structures as requested on the NEA course and mentioned in issue #2043

2022-04-27 15:20 UTC, nelsonag requested changes
Hi @shimwell, I just took a look and put in a few minor comments. In general, I think the SCALE-44 structure is used widely enough to warrant being included with the structures we already have present.

Thanks!

2022-04-27 16:32 UTC, shimwell commented on openmc/mgxs/__init__.py
> +    50.e6]),
Thanks, I've removed the comma now

2022-04-27 16:33 UTC, shimwell commented on openmc/mgxs/__init__.py
> +GROUP_STRUCTURES['SCALE-44'] = np.array([3.e-3, 7.5e-3, 1.e-2, 2.53e-2, 3.e-2,
Thanks yes that should be added

2022-04-27 16:33 UTC, shimwell commented on openmc/mgxs/__init__.py
> +    1.85e6, 2.354e6, 2.479e6, 3.e6, 4.8e6, 6.434e6, 8.1873e6, 2.e7]),
thanks

2022-04-27 17:53 UTC, nelsonag approved these changes

2022-04-28 11:39 UTC, paulromano commented
@shimwell Thanks for this PR. While you're at it, can you fix the following line? Looks like an extra comma snuck into one of the dictionary keys by accident.
```diff
diff --git a/openmc/mgxs/__init__.py b/openmc/mgxs/__init__.py
index 133b4c257..938dd8c7a 100644
--- a/openmc/mgxs/__init__.py
+++ b/openmc/mgxs/__init__.py
@@ -154,7 +154,7 @@ GROUP_STRUCTURES['VITAMIN-J-175'] = np.array([
     1.1052e7, 1.1618e7, 1.2214e7, 1.2523e7, 1.2840e7, 1.3499e7,
     1.3840e7, 1.4191e7, 1.4550e7, 1.4918e7, 1.5683e7, 1.6487e7,
     1.6905e7, 1.7332e7, 1.9640e7])
-GROUP_STRUCTURES['TRIPOLI-315,'] = np.array([
+GROUP_STRUCTURES['TRIPOLI-315'] = np.array([
     1.0e-5, 1.1e-4, 3.000e-3, 5.500e-3, 1.000e-2, 1.500e-2, 2.000e-2, 3.000e-2,
     3.200e-2, 3.238e-2, 4.300e-2, 5.900e-2, 7.700e-2, 9.500e-2, 1.000e-1,
     1.150e-1, 1.340e-1, 1.600e-1, 1.890e-1, 2.200e-1, 2.480e-1, 2.825e-1,
```

2022-04-28 19:25 UTC, paulromano approved these changes

2022-04-28 19:25 UTC, merged