added bin_log_width to EnergyFilter() to help with plotting
openmc-dev/openmc pull request #2154
Opened 2022-08-08 12:54 UTC by shimwell

Just wondering if we can add a few lines to the ```EnergyFilter``` class that allows one to conveniently access the log bin width.

This can useful when plotting spectra

```python
import matplotlib.pyplot as plt
import numpy as np 

results = openmc.StatePoint(results_filename)
cell_tally = results.get_tally(name='cell_spectra_tally')
energy_filter = cell_tally.find_filter(filter_type=openmc.filter.EnergyFilter)

bin_boundaries = energy_filter.bin_log_width()
flux = cell_tally.mean.flatten()
norm_flux = flux / bin_boundaries

plt.figure(figsize=(16,9))
plt.step(np.unique(energy_filter.bins)[:-1], flux)
plt.step(np.unique(energy_filter.bins)[:-1], norm_flux)
plt.xscale('log')
plt.yscale('log')
plt.show()
```

2022-08-08 16:23 UTC, eepeterson commented
If you want to add a function like this I'd recommend just a property called `lethargy` with `return np.log(self.bins[:, 1]/self.bins[:, 0])`

2022-08-08 16:35 UTC, paulromano commented
@eepeterson I think lethargy is usually defined relative to some reference energy, i.e. something like `np.log10(E_reference / energies)` where `E_reference` is a scalar and `energies` is an array. That is slightly different than what is proposed (ratio of successive energies).

2022-08-08 16:44 UTC, eepeterson commented
> @eepeterson I think lethargy is usually defined relative to some reference energy, i.e. something like `np.log10(E_reference / energies)` where `E_reference` is a scalar and `energies` is an array. That is slightly different than what is proposed (ratio of successive energies).

You're right, it could be called `bin_lethargy` to be clearer, but I think the point is to be able to plot spectra with different group structures on the same plot and have them be comparable.

2022-08-08 16:54 UTC, shimwell commented
Thanks for the feedback, I've renamed the method to ```bin_lethargy```

We could add another method  ```def lethargy(self, E_reference):``` if desired

2022-08-08 17:13 UTC, paulromano requested changes
In addition to the line comments, this PR also needs a quick unit test.

2022-08-08 17:13 UTC, paulromano commented on openmc/filter.py
> +    def bin_lethargy(self):
Let's make this a property. Also, I'd suggest the following name:
```suggestion
    @property
    def lethargy_bin_width(self):
```

2022-08-08 17:13 UTC, paulromano commented on openmc/filter.py
> +        return log_width
```suggestion
        return np.log10(self.bins[:, 1]/self.bins[:, 0])
```

2022-08-08 17:14 UTC, paulromano commented on openmc/filter.py
> +    def bin_lethargy(self):
You'll also need to add a description of this new property to the class docstring

2022-08-09 11:37 UTC, paulromano commented on tests/unit_tests/test_filters.py
> +def test_lethargy_bin_width():
PEP8: [Surround top-level function and class definitions with two blank lines](https://peps.python.org/pep-0008/#blank-lines)

2022-08-09 11:38 UTC, shimwell commented
I would be keen to get rid of the need for users to do ```np.unique(energy_filter.bins)[:-1]``` when calling ```plt.step()``` as well.

What do people think of adding a ```def bin_edges(self)``` property that returns ```np.unique(self.bins)``` to make things even easier for the user or is that a **step** too far :drum:

2022-08-09 11:45 UTC, paulromano commented
@shimwell The `values` property already gives just an array of the energies. I think that's what you're looking for?

2022-08-09 11:48 UTC, shimwell commented
> 

Oh yes, that works, thanks. I shall update the example at the top of this PR.

2022-08-09 12:05 UTC, paulromano approved these changes
Thanks!

2022-08-10 02:56 UTC, merged