`IndependentOperator` hotfix
openmc-dev/openmc pull request #2158
Opened 2022-08-10 02:56 UTC by yardasol

This PR is a hotfix for `IndependentOperator` functionality. While doing more extensive testing, I discovered there was an implementation error: we were multiplying the fission cross sections by material volume and nuclide density in the inner normalization helper `_IndependentNormalizationHelper`, but this was already being done in `_IndependentRateHelper`, hence we were obtaining results that were way off of what they should been relative to a coupled case. 

This could have been prevented if a more robust regression test were present, so I have also added additional functionality to test results from a transport-coupled depletion calculation and a transport-independent depletion calculation over several timestep sizes.

2022-08-10 19:32 UTC, yardasol commented on docs/source/usersguide/depletion.rst
> +      \phi = \frac{P}{V \cdot \sum_i (Q_i \cdot \sigma^f_i \cdot \rho_i)}
```suggestion
      \phi = \frac{P}{V \cdot \sum_i (Q_i \cdot \sigma^f_i \cdot \n_i)}
```

2022-08-11 12:42 UTC, paulromano requested changes

2022-08-11 12:42 UTC, paulromano commented on docs/source/pythonapi/deplete.rst
> +provides The following classes implement transport operators:
```suggestion
provides the following transport operator classes:
```

2022-08-11 18:35 UTC, yardasol commented on openmc/deplete/openmc_operator.py
> +        print(f"flux, power, or source rate: {self._normalization_helper.factor(source_rate)}")
whoops, forgot to remove this!

2022-08-12 12:09 UTC, paulromano requested changes

2022-08-12 12:09 UTC, paulromano commented on openmc/deplete/microxs.py
> +            statepoint_path = model.run(cwd=temp_dir, **run_kwargs)
I wouldn't put `init_lib()` within here. If a user wants to have things run through `openmc.lib`, they can call `model.init_lib()` themselves prior to calling `MicroXS.from_model`. Also, using the `setdefault` method on a dictionary can help clean this up:
```suggestion
            run_kwargs.setdefault('cwd', temp_dir)
            statepoint_path = model.run(**run_kwargs)
```

2022-08-15 12:00 UTC, paulromano approved these changes
Thanks for the fixes @yardasol!

2022-08-15 12:00 UTC, merged