added optional nuclide to atom densities
openmc-dev/openmc pull request #2188
Opened 2022-08-23 15:36 UTC by shimwell

The ```openmc.Material.get_nuclide_atom_densities()``` currently returns all of the nuclide in the material.

Other methods such as ```openmc.Material.get_mass_density``` support the ability to specify the nuclide of interest and get a single nuclide back.

This PR adds a ```nuclide``` argument o the  ```openmc.Material.get_nuclide_atom_densities()``` method which is in keeping with the  ```openmc.Material.get_mass_density``` and will also be useful to some other use cases that I'm working on (figuring out if nuclide are in their natural abundance so they can be squashed to elements).

I've added to the doc string and added a simple test to the unit tests.

2022-08-23 22:19 UTC, shimwell commented on tests/unit_tests/test_material.py
> +    print(uo2)
```suggestion
```

2022-08-23 22:20 UTC, shimwell commented on tests/unit_tests/test_material.py
> +
```suggestion
```

2022-08-25 14:07 UTC, paulromano requested changes

2022-08-25 14:07 UTC, paulromano commented on openmc/material.py
> +            atom density for the all the material is given.
```suggestion
            atom density for each nuclide in the material is given.
```

2022-08-25 14:07 UTC, paulromano commented on openmc/material.py
> +            atom density for the all the material is given.
This parameters section needs to be below the `.. versionchanged:: 0.13.1` directive

2022-08-25 14:07 UTC, paulromano commented on openmc/material.py
> +            nuc_density_types.append(loop_nuclide.percent_type)
```suggestion
        for nuc in self.nuclides:
            nucs.append(nuc.name)
            nuc_densities.append(nuc.percent)
            nuc_density_types.append(nuc.percent_type)
```

2022-08-25 14:07 UTC, paulromano commented on tests/unit_tests/test_material.py
> +def test_get_specific_nuclide_atom_densities(uo2):
```suggestion
def test_get_nuclide_atom_densities_specific(uo2):
```

2022-08-25 14:29 UTC, paulromano approved these changes

2022-08-26 12:33 UTC, merged