Fix errorneous behavior when adding metastable nuclides via `add_components`
openmc-dev/openmc pull request #2205
Opened 2022-09-01 16:54 UTC by yardasol

When writing `add_components`, I seem to have forgotten to test whether it worked with metastable nuclides. The previous version of the function incorrectly sent metastable nuclides to the `add_elements` function, which resulted in an error. This PR fixes that behavior and adds a metastable case to the unit test.

2022-09-01 19:29 UTC, paulromano requested changes

2022-09-01 19:29 UTC, paulromano commented on openmc/material.py
> +                                              and str.isdigit(component[-2])):
```suggestion
            if not str.isalpha():
```

2022-09-01 19:29 UTC, paulromano commented on tests/unit_tests/test_material.py
> +                  'Ag110m': 1.0,
Our format for metastables is as follows:
```suggestion
                  'Ag110_m1': 1.0,
```

2022-09-01 19:34 UTC, yardasol commented on openmc/material.py
> +                                              and str.isdigit(component[-2])):
Much cleaner!

2022-09-01 19:44 UTC, paulromano approved these changes

2022-09-02 17:07 UTC, paulromano commented on openmc/material.py
> +            if not str.isalpha():
Oops, sorry for leading you astray. This should have been
```suggestion
            if not component.isalpha():
```

2022-09-07 21:45 UTC, merged