Add paragraph to User Guide on using `MicroXS.from_model` on clusters
openmc-dev/openmc pull request #2212
Opened 2022-09-08 16:41 UTC by yardasol

This PR replaces #2180.

It adds a paragraph to the User's Guide on what to do if a user wants to run `MicroXS.from_model` on a cluster that doesn't share local filesystems across nodes.

Closes #2177 and #2172

2022-09-08 17:20 UTC, paulromano requested changes

2022-09-08 17:20 UTC, paulromano commented on docs/source/usersguide/depletion.rst
> +that does not share local filesystems across nodes, you'll need to set an
```suggestion
If you are runnig :meth:`~openmc.deplete.MicroXS.from_model()` on a cluster
where temporary files are created on a local filesystem that is not shared across nodes, you'll need to set an
```

2022-09-08 17:20 UTC, paulromano commented on docs/source/usersguide/depletion.rst
> +are `TMPDIR`. `TEMP`, and `TMP`. Users interested in further details can read
```suggestion
are :envvar:`TMPDIR`. :envvar:`TEMP`, and :envvar:`TMP`. Users interested in further details can read
```

2022-09-08 17:20 UTC, paulromano commented on docs/source/usersguide/depletion.rst
> +the `relevant docpage on the tempfile pacakge <https://docs.python.org/3/library/tempfile.html#tempfile.gettempdir>`_
```suggestion
the documentation for the `tempfile <https://docs.python.org/3/library/tempfile.html#tempfile.gettempdir>`_ module.
```

2022-09-08 18:58 UTC, paulromano requested changes

2022-09-08 18:58 UTC, paulromano commented on docs/source/usersguide/depletion.rst
>  -------------------------------------
```suggestion
Loading and Generating Microscopic Cross Sections
-------------------------------------------------
```

2022-09-08 18:58 UTC, paulromano commented on docs/source/usersguide/depletion.rst
> +pre-caluclated cross sections from a ``.csv`` file or from data arrays::
```suggestion
pre-calculated cross sections from a ``.csv`` file or from data arrays::
```

2022-09-08 18:58 UTC, paulromano commented on docs/source/usersguide/depletion.rst
> +A transport-independent depletion simulation using ``source-race`` normalization
```suggestion
A transport-independent depletion simulation using ``source-rate`` normalization
```

2022-09-11 19:04 UTC, yardasol commented
I made the language a little more precise in some areas. Also I've confirmed the described approach works!

2022-09-15 04:15 UTC, paulromano approved these changes

2022-09-15 04:16 UTC, merged

2022-09-15 04:16 UTC, paulromano commented
Thanks @yardasol!