Add a cache system for the depletion material reaction rates tally
openmc-dev/openmc pull request #2218
Opened 2022-09-10 01:38 UTC by joshmay1

With each burnable material, the reaction rates tallies are read from the DLL when accessing the `_rate_tally.mean`. Then, the specific material desired is indexed from this tally. This causes the transmutation time to significantly increase with the depletable material count. This proposed change reads the tally results once per transmutation cycle and stores the results in a cache. The cache is then used for all subsequent depletable materials when accessing their rates. At the beginning of each cycle, the cache is reset so the new tally results can be read back in.

2022-09-10 18:36 UTC, drewejohnson requested changes
Thanks for this clever solution @joshmay1. I've got some minor requests on documentation but it looks good to me :+1:

2022-09-10 18:36 UTC, drewejohnson commented on openmc/deplete/helpers.py
> +    def rate_tally_means(self):
Can you add a docstring, even a one-liner, for this now public property?

2022-09-10 18:36 UTC, drewejohnson commented on openmc/deplete/helpers.py
> +        This step must be performed after each transport cycle
Minor update to adhere to the numpydoc spec
```suggestion

    .. note::
        
            This step must be performed after each transport cycle
```

2022-09-10 18:36 UTC, drewejohnson commented on openmc/deplete/helpers.py
> +        # If the mean cache is empty, fill it once for this transport cycle's results
Same request for docstrings on public properties

2022-09-10 18:36 UTC, drewejohnson commented on openmc/deplete/helpers.py
> +        This step must be performed after each transport cycle
```suggestion
        .. note::
        
            This step must be performed after each transport cycle
```

2022-09-10 18:36 UTC, drewejohnson commented on openmc/deplete/helpers.py
> +
Extra new line between methods
```suggestion
```

2022-09-12 17:11 UTC, joshmay1 commented
Thanks for the review @drewejohnson! I believe I addressed all of your comments now.

2022-09-15 12:12 UTC, paulromano approved these changes
Looks good to me. Thanks @joshmay1!

@drewejohnson Do you have any further comments on this PR?

2022-09-19 03:41 UTC, drewejohnson approved these changes
Sorry for the delay! Thanks @joshmay1

No further requests

2022-09-19 03:41 UTC, merged