FilterType Enumerator
openmc-dev/openmc pull request #2293
Opened 2022-11-06 05:10 UTC by pshriwise

Resolves #2292.

This adds a `FilterType` enumerator. It is used to replace the return type of the `Filter::type` static method. The string identifiers have been moved to the `Filter::type_str()` method, which is still used to write the filter type to the statepoint file.

2022-11-09 22:22 UTC, paulromano requested changes

2022-11-09 22:23 UTC, pshriwise commented on include/openmc/tallies/filter.h
> +  AZIMUTHAL = 0,
Thanks!! 🙏🏻

2022-11-10 13:31 UTC, paulromano requested changes

2022-11-10 13:31 UTC, paulromano commented on openmc/filter.py
> +                  'removed in the future.')
```suggestion
                  'removed in the future.', FutureWarning)
```

2022-11-10 21:05 UTC, merged