Fix bug in `openmc.Universe.get_nuclide_densities()`
openmc-dev/openmc pull request #2310
Opened 2022-11-29 04:18 UTC by joshmay1

In the Universe object, the `_atoms` attribute is initialized to an empty dictionary. This attribute is only set once volumes are added to the universe. When the `get_nuclide_densities()` method is called, a check is present to ensure volumes have been set before returning the nuclide densities. The check was invalid, meaning the Exception was not raised and an empty nuclide dictionary was instead returned. This PR corrects this bug by ensuring the Exception is properly raised.

2022-11-29 19:34 UTC, paulromano requested changes
Thanks for the small fix @joshmay1! Two small comments below:

2022-11-29 19:34 UTC, paulromano commented on openmc/universe.py
> +        if len(self._atoms) > 0:
Alternatively, you could use the "truthiness" of the object (`dict` is considered True if it is non-empty)
```suggestion
        if self._atoms:
```

2022-11-29 19:34 UTC, paulromano commented on tests/unit_tests/test_universe.py
> +    cell = openmc.Cell(region=-surf,fill=material)
```suggestion
    cell = openmc.Cell(region=-surf, fill=material)
```

2022-11-30 01:00 UTC, joshmay1 commented
You're welcome @paulromano. I addressed your comments!

2022-11-30 02:47 UTC, paulromano approved these changes

2022-11-30 03:49 UTC, paulromano commented
This fix is pretty straightforward so I'm going to forgo the normal 36 hour review period and merge. Thanks again @joshmay1!

2022-11-30 03:49 UTC, merged