Prompt neutrons
openmc-dev/openmc pull request #2327
Opened 2022-12-13 01:49 UTC by cfichtlscherer

This new feature should allow users to simulate the prompt criticality of their system. Which is the criticality based only on the prompt fission neutrons. Therefore, you can now decide whether delayed neutrons are created during fission.

That's how it would look in practice:
`settings.create_delayed_neutrons = False` 

I hope someone finds this useful, and I am looking forward to your feedback.

2022-12-13 19:35 UTC, cfichtlscherer commented
Did someone had this error in the docs before?

`Failed to checkout revision: a029c59f2a497a9f9b74f4a7df5237842e0fa1a0`

I just changed a boolean variable which created this error somehow.

Thanks a lot already.

2022-12-31 03:23 UTC, paulromano requested changes

2022-12-31 03:23 UTC, paulromano commented on src/nuclide.cpp
> +  if (object_exists(group, "total_nu") && settings::create_delayed_neutrons) {
@cfichtlscherer I know we had talked about this offline. On second thought, I think the most rigorous way of handling this option is to check `create_delayed_neutrons` inside the `Nuclide::nu` method. When `EmissionMode::delayed` is passed, `nu(...)` should return 0 and when `EmissionMode::total` is passed, it should return the prompt value. This ensures that any other uses of `nu(...)` reflect the same option (e.g., in tallies).
```suggestion
  if (object_exists(group, "total_nu")) {
```

2023-01-11 03:16 UTC, paulromano requested changes
Code looks good now -- thanks for the update @cfichtlscherer! I like how simple it ended up being. I did a quick check using this new option to calculate β<sub>eff</sub> for Godiva and Jezebel using the prompt method (1 - k<sub>p</sub>/k) and the results are close to that reported in [Meulekamp](https://doi.org/10.13182/NSE03-107).

Other than the line comment below, can you also update `tests/unit_tests/test_settings.py` to include this new attribute?

2023-01-11 03:16 UTC, paulromano commented on openmc/settings.py
> +        .. versionadded:: 0.13
Can you change the version to 0.13.3 and move this up in the last of attributes (they are listed alphabetically)?

2023-01-11 18:24 UTC, closed without merging

2023-01-11 18:54 UTC, cfichtlscherer commented
Closed by accident and reopened in another pull request.