Manually instantiate cloned cells rather than deepcopying
openmc-dev/openmc pull request #2340
Opened 2023-01-05 00:32 UTC by joshmay1

These changes replace the deepcopying of cloned cells with a manual new instantiation. Any present optional cell properties are applied to the clone. Depending on cloning settings, the fill and region properties are set accordingly as before.

This provides a noticeable and significant performance improvement, particularly when cloning complicated cells, because it removes the potential for extra steps. With the deepcopy method, the original cell's fill and region attributes were deepcopied and immediately overwritten.

2023-01-11 07:35 UTC, paulromano requested changes
Thanks for another performance improvement @joshmay1! Only a few trivial comments:

2023-01-11 07:35 UTC, paulromano commented on openmc/cell.py
> +            clone.name = self.name
```suggestion
            clone = openmc.Cell(name=self.name)
```

2023-01-11 07:35 UTC, paulromano commented on tests/unit_tests/test_cell.py
> +    c.rotation = [4,5,6]
```suggestion
    c.translation = (1., 2., 3.)
    c.rotation = (4., 5., 6.)
```

2023-01-11 07:35 UTC, paulromano commented on tests/unit_tests/test_cell.py
> +    c.rotation = [-4,-5,-6]
```suggestion
    c.translation = (-1., -2., -3.)
    c.rotation = (-4., -5., -6.)
```

2023-01-12 00:36 UTC, joshmay1 commented
You're welcome @paulromano and thanks for the review! Similar changes can be made to universe cloning as well. I'll get a PR up with those soon.

2023-01-12 02:48 UTC, paulromano approved these changes

2023-01-12 02:48 UTC, merged