Prompt neutrons 2.0
openmc-dev/openmc pull request #2348
Opened 2023-01-11 20:35 UTC by cfichtlscherer

This is a follow-up on the pull request [prompt neutrons](https://github.com/openmc-dev/openmc/pull/2327).

2023-01-12 02:52 UTC, paulromano requested changes

2023-01-12 02:52 UTC, paulromano commented on openmc/settings.py
> +        settings._create_delayed_neutrons_from_xml_element(root)
```suggestion
        settings._create_delayed_neutrons_from_xml_element(elem)
```

2023-01-12 02:52 UTC, paulromano commented on openmc/settings.py
>          .. versionadded:: 0.13
```suggestion
        .. versionadded:: 0.13
    create_delayed_neutrons : bool
        Whether delayed neutrons are created in fission.

        .. versionadded:: 0.13.3
```

2023-01-12 11:26 UTC, cfichtlscherer commented on openmc/settings.py
> +        settings._create_delayed_neutrons_from_xml_element(root)
thanks!

2023-01-13 02:44 UTC, paulromano approved these changes
Looks good this time around. Thanks for the new feature @cfichtlscherer!

2023-01-13 02:44 UTC, merged