allowing materials.xml to be specified
openmc-dev/openmc pull request #2364
Opened 2023-01-27 14:33 UTC by shimwell

The ```Results.export_to_materials``` method in ```openmc.deplete``` is super useful.

This PR is an attempt to make it a tiny bit more flexible by allowing the path to the materials.xml to be specified.

This is useful when running multiple depletion steps and wanting to get the materials for a seperate folder or elsewhere.

It is useful to have the different stages stored in separate file locations so that the materials at each time step can be investigated.

Would you be able to review @eepeterson as this is similar to changes you had in your R2SModel branch but I've tried to use the path argument in the same way it is used elsewhere in openmc (e.g. [here](https://github.com/openmc-dev/openmc/blob/3f5b90042c378f4182ef196ac075dd8cd8cec686/openmc/material.py#L1587))

2023-01-27 19:12 UTC, eepeterson commented
Thanks @shimwell! This is indeed helpful for those workflows.

2023-01-27 19:12 UTC, eepeterson approved these changes

2023-01-28 12:15 UTC, paulromano requested changes

2023-01-28 12:15 UTC, paulromano commented on openmc/deplete/results.py
> +            Path to file to write. Defaults to 'materials.xml'.
The method below doesn't write to materials.xml. Instead, it uses an _existing_ materials.xml as the basis for generating an updated `Materials` object. The description here needs to be changed to reflect that.

2023-01-28 17:18 UTC, shimwell commented on openmc/deplete/results.py
> +            Path to file to write. Defaults to 'materials.xml'.
```suggestion
            Path to materials XML file to read. Defaults to 'materials.xml'.
```

2023-01-31 12:16 UTC, paulromano approved these changes

2023-01-31 14:02 UTC, shimwell commented
I have merged in the latest develop branch (which fixes the CI) and am now rerunning the tests as I think that a pass is required to merge this PR

2023-01-31 19:09 UTC, shimwell commented
Super tests are passing, I think this is ready to merge

2023-01-31 19:33 UTC, merged

2023-01-31 19:34 UTC, paulromano commented
Thanks @shimwell. For future reference, you don't actually need to merge in develop to your branch. When CI runs, it is actually testing a merge commit, so just retriggering CI once the `develop` branch is updated should be sufficient.