added volume information to material repr
openmc-dev/openmc pull request #2377
Opened 2023-02-07 12:31 UTC by shimwell

Hi all, another tiny PR for your consideration

I'm doing a few depletion simulations and this requires adding volume information to each material.

It would be useful for me at least if the ```material.__repr__``` included the volume information.

Then when a material is printed it will display volume along with other handy things like name, density, temperature etc and I can easily see which of my materials still need volume adding

before this PR
```
 Material
	ID             =	8
	Name           =	mat_suspended_floor
	Temperature    =	None
	Density        =	7.82 [g/cm3]
	S(a,b) Tables  
	Nuclides       
	Fe54           =	0.057115528049999996 [ao]
```

after this PR
```
 Material
	ID             =	8
	Name           =	mat_suspended_floor
	Temperature    =	None
	Density        =	7.82 [g/cm3]
	Volume         =	1.2709345346346374e+26 [cm3]
	S(a,b) Tables  
	Nuclides       
	Fe54           =	0.057115528049999996 [ao]
```

2023-02-07 13:07 UTC, shimwell commented
oh i see this has been proposed in #2368

closing in favor of #2368

2023-02-23 21:16 UTC, shimwell commented on openmc/material.py
> +        string += ' [cm3]\n'
```suggestion
        string += ' [cm^3]\n'
```

2023-02-23 21:24 UTC, shimwell commented
reopened as it looks like #2368 is not going ahead

2023-02-24 19:39 UTC, paulromano requested changes

2023-02-24 19:39 UTC, paulromano commented on openmc/material.py
> +        string += ' [cm^3]\n'
```suggestion
        string += '{: <16}=\t{} [cm^3]\n'.format('\tVolume', self._volume)
```

2023-02-25 02:44 UTC, paulromano approved these changes

2023-02-25 02:44 UTC, merged