Updates to batch checks for simulation restarts
openmc-dev/openmc pull request #2390
Opened 2023-02-16 19:53 UTC by pshriwise

Resolves #2389 

Additional changes:
  - change to allow `openmc.Pathlike` to be passed for the restart file in the Python API
  - "Pathlike" --> "PathLike" in docstrrings

2023-02-16 22:31 UTC, pshriwise commented
A couple more updates here:

  - Added a line that searches for the subelement `<type>` in `<filter>` nodes to support backward compatibility with older XML files (including those in our test suite)
  - Changed the comparison in `load_state_point` to use `settings::n_max_batches` to support continuation runs that use triggers

2023-02-21 05:31 UTC, paulromano requested changes

2023-02-21 05:31 UTC, paulromano commented on tests/regression_tests/statepoint_restart/test.py
> +import pytest
```suggestion
import openmc
import pytest

from tests.testing_harness import TestHarness
from tests.regression_tests import config
from tests import cdtemp
```

2023-02-21 06:41 UTC, pshriwise commented on openmc/executor.py
> +    if isinstance(restart_file, PathLike.__args__):
Yeahh, I agree. I was hoping to be able to make it `openmc.PathLike`, but while this was added in [PEP604](https://peps.python.org/pep-0604/) it seems that isn't available in versions before 3.10.

The nice thing about this approach is that any other types we might include in that `typing.Union` would automatically get checked here, but I don't see that happening anytime soon. In short, I'll be more explicit :)

2023-02-21 12:49 UTC, paulromano requested changes
One more little pathlib trick for ya:

2023-02-21 12:49 UTC, paulromano commented on tests/regression_tests/statepoint_restart/test.py
> +        statepoint = list(Path(os.getcwd()).glob(self._restart_sp))
```suggestion
        statepoint = list(Path.cwd().glob(self._restart_sp))
```

2023-02-21 13:18 UTC, pshriwise commented on tests/regression_tests/statepoint_restart/test.py
> +        statepoint = list(Path(os.getcwd()).glob(self._restart_sp))
Ooooooh neat!

2023-02-22 15:16 UTC, merged