Additional DAGMC test for lost particles
openmc-dev/openmc pull request #2434
Opened 2023-03-22 03:12 UTC by pshriwise

This is one I've been meaning to add for a while. I was recently prompted by some discussion in #1926.

I've taken the DAGMC pincell model we use in a few other tests and removed 100 random triangles from the surfaces of the cladding volume to ensure that we'd encounter some situations in which an intersection with the particle's DAGMC cell cannot be found. 

One of the main purposes of this test is to ensure that lost particles are caught correctly in DAGMC models not only when the DAGMC model is the root universe, but also when DAGMC universes are used to fill other cells.

@gridley  raise a very good question in #1926 about why the `DAGCell::contains` method handles a missing intersection differently by marking the particle as lost in the method rather than a like `CSGCell`, which returns an invalid surface index and an infinite intersection distance. 

For DAGMC universes that are used as the root universe of the geometry, we can expect that a finite intersection distance is _always_ found. If this were the only way to use DAGMC universes, we could return the same behavior as `CSGSurfaces` without a problem. 

But in the case that a DAGMC universe is used as a universe filling a cell or lattice, an infinite intersection distance isn't valid _unless_ the particle is in the implicit complement. If the particle is in the implicit complement, we need to allow for the case that the particle has left all explicitly defined regions of the DAGMC model and will travel up to the boundary of the containing cell/lattice cell to continue transport. If we were to use the same behavior as the `CSGCell` in this case and return an infinite intersection distance, a missed intersection in an explicitly defined DAGMC volume that should result in a lost particle will allow the particle to jump to the boundary of the containing cell through all other volumes in the DAGMC model because of how our surface intersection logic works -- the particle would intersect with the nearest surface higher up in the geometry hierarchy. So, because there isn't a way (that I can see) to capture this nuance for DAGMC universes, we need to report the particle as lost in the `DAGCell::distance` method.*

That was really lengthy... I can provide a diagram if requested by the reviewer.

I also updated `lattice.py` to use `openmc.UniverseBase` instead of `openmc.Universe`  because it was breaking the `Lattice.get_all_universes` method when DAGMC universes are present. This update is now tested in some of the lines of code in the new test here.

* Noting here that while writing this I realized that this doesn't cover a case where we are in the implicit complement of a DAGMC universe filling a cell/lattice cell and we _should_ get a finite intersection distance but don't (due to watertightness issues). I'm not sure how we'd detect that offhand and will give it some thought.

2023-03-22 18:15 UTC, pshriwise commented
> Makes sense to me! CSG surfaces cannot have holes, while mesh surfaces may. Cool.
> 
> (or can they? The new torus surfaces _can_ have a hole so we may be missing some weird particle leak edge case there)

Not quite sure what you mean here. As in there's a known particle leakage problem for torus surfaces?

> I'll give this some time so you can figure out a good solution to that last issue.

Thought about this some more this morning. Regardless of whether the fill universe is composed of CSG or DAGMC cells, the scenario in which a particle doesn't intersect correctly with its current cell and immediately "jumps" to the boundary of the universe's containing cell is something we generally can't handle with our current approach. Because this isn't a problem that's unique to DAGMC universes, I think we can proceed with the PR and address the [new issue](https://github.com/openmc-dev/openmc/issues/2438) I made related to this topic separately.

2023-03-23 16:28 UTC, pshriwise commented
> Should we not mark the particle as lost in dagmc if we're in plotting mode, then? This PR would be the place to add that behavior.

Yeah, that would be my suggestion for now. Should be a one-liner in that block that marks particles as lost in the `DAGCell`.

2023-03-31 01:58 UTC, gridley commented
I would review this, but am not familiar enough with DAGMC to provide any useful feedback! Generally, the changes look good to me.

2023-04-13 08:53 UTC, shimwell commented
I was just skimming through the open PRs and noticed that a single conflict has crept into this one. I don't trust myself with the C++ enough to resolve it sorry

2023-04-13 15:27 UTC, pshriwise commented
Thanks @shimwell! Just resolved that conflict 👍🏻

2023-04-13 20:13 UTC, paulromano requested changes
A few comments here on the test. Otherwise the code looks good to me -- would appreciate a second look from someone more familiar with DAGMC if possible (@shimwell @makeclean)

2023-04-13 20:13 UTC, paulromano commented on tests/unit_tests/dagmc/test_lost_particles.py
> +    water.add_nuclide('B11', 3.2218e-05)
Can you cut these down to a single nuclide each? It's not important for the sake of the test and results in more time in the test just loading cross sections

2023-04-13 20:13 UTC, paulromano commented on tests/unit_tests/dagmc/test_lost_particles.py
> +    bounding_cell = openmc.Cell(fill=lattice, region=bounding_region)
```suggestion
    # clip the DAGMC geometry at +/- 10 cm w/ CSG planes
    rpp = openmc.model.RectangularParallelepiped(
        -pitch[0], pitch[0], -pitch[1], pitch[1], -10.0, 10.0, boundary_type='reflective')
    bounding_cell = openmc.Cell(fill=lattice, region=-rpp)
```

2023-04-13 20:13 UTC, paulromano commented on tests/unit_tests/dagmc/test_lost_particles.py
> +    model.settings.output = {'summary' : False}
```suggestion
    model.settings.output = {'summary': False}
```

2023-04-13 20:13 UTC, paulromano commented on tests/unit_tests/dagmc/test_lost_particles.py
> +    model = openmc.model.Model()
```suggestion
    model = openmc.Model()
```

2023-04-14 17:34 UTC, paulromano approved these changes
Thanks @pshriwise! I'll let this sit over the weekend in case others have thoughts.

2023-04-17 14:41 UTC, merged