Add support for ncrystal materials
openmc-dev/openmc pull request #2435
Opened 2023-03-22 15:49 UTC by zoeprieto

This pull request aims to fix the issue #2422. The changes are simple but one remaining point would be to obtain the maximum NCrystal energy from the C API. @paulromano how can we access the API to obtain NCRYSTAL_MAX_ENERGY?

2023-03-22 15:59 UTC, zoeprieto commented
```
cfg = 'LiquidWaterH2O_T293.6K.ncmat'
m1 = openmc.Material.from_ncrystal(cfg)
m1.name = cfg
openmc.plot_xs(m1, ('scatter',))
```
![image](https://user-images.githubusercontent.com/101403129/226964510-1e0fbcea-8141-46a3-bfc9-708c361a102f.png)


Here there is a simple example

2023-03-23 19:19 UTC, paulromano requested changes
Thanks for implementing this @zoeprieto! It looks like there is a conflict in plotter.py due to the recently merged PR #2413, so you'll need to merge in the latest develop branch into your branch and resolve the conflicts.

2023-03-23 19:19 UTC, paulromano commented on openmc/plotter.py
> +                        nc_emax = 5 # eV # this should be obtained from NCRYSTAL_MAX_ENERGY
I think there was some discussion about having the max energy be configurable, but I forget where we ended up on this. @tkittel Do you recall? In any event, I'm fine with the hard-coded value for now.

2023-03-30 18:59 UTC, zoeprieto commented
Hey @paulromano , I incorporated the changes to my branch. Can you please review it again?

2023-04-13 20:14 UTC, paulromano approved these changes
Thanks @zoeprieto!

2023-04-13 20:14 UTC, merged