added return types
openmc-dev/openmc pull request #2462
Opened 2023-04-07 19:33 UTC by christinacai123

2023-04-07 20:58 UTC, paulromano requested changes
Thanks for contribution @christinacai123! (and thanks to @shimwell for helping guide some first-time contributors). For the suggested changes below, note that you can [batch them together as one commit](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/incorporating-feedback-in-your-pull-request#applying-suggested-changes) directly in the web interface.

2023-04-07 20:58 UTC, paulromano commented on openmc/weight_windows.py
>  from numbers import Real, Integral
Our Python code follows [PEP8](https://peps.python.org/pep-0008/), which recommends grouping imports into three groups: standard-library modules, third-party modules, and local imports. In your case, both `__future__` and `typing` are standard-library and should be in the first block:
```suggestion
from __future__ import annotations
from collections.abc import Iterable
from numbers import Real, Integral
from typing import Iterable, List
```

2023-04-07 20:58 UTC, paulromano commented on openmc/weight_windows.py
> +
```suggestion
```

2023-04-07 20:58 UTC, paulromano commented on openmc/weight_windows.py
> +    def lower_ww_bounds(self) -> Iterable[Real]:
When this attribute is set, it is converted to a numpy array, so this should probably be:
```suggestion
    def lower_ww_bounds(self) -> np.ndarray:
```

2023-04-07 20:58 UTC, paulromano commented on openmc/weight_windows.py
> +    def upper_ww_bounds(self) -> Iterable[Real]:
```suggestion
    def upper_ww_bounds(self) -> np.ndarray:
```

2023-04-07 20:58 UTC, paulromano commented on openmc/weight_windows.py
> +def wwinp_to_wws(path) -> WeightWindows:
This actually returns a list of weight windows:
```suggestion
def wwinp_to_wws(path) -> List[WeightWindows]:
```

2023-04-07 21:37 UTC, shimwell commented
Super to see you made it from discourse to GitHub so quickly. Nice one

Hit all the "add suggestion to batch" buttons on [this](https://github.com/openmc-dev/openmc/pull/2462/files) page as the next step

2023-04-10 16:58 UTC, christinacai123 reviewed
added suggestions to weight_windows.py

2023-04-10 19:51 UTC, paulromano approved these changes
Looks good to me! Will merge once CI passes.

2023-04-11 01:33 UTC, merged