moved voxel plot to api accessible function
openmc-dev/openmc pull request #2464
Opened 2023-04-11 17:07 UTC by shimwell

This issue moves some code from a python script to the python api

The script retains it's original functionality as it calls the python api

The benefit is that this allows one to make a voxel plot from the python api as well as running the conversion script form the terminal.

before this PR
```
import os
import openmc
surf1 = openmc.Sphere(r=500, boundary_type='vacuum')
cell1 = openmc.Cell(region=-surf1)
geometry = openmc.Geometry([cell1])
geometry.export_to_xml()
materials = openmc.Materials()
materials.export_to_xml()
vox_plot = openmc.Plot()
vox_plot.type = 'voxel'
vox_plot.id = 12
vox_plot.width = (1500., 1500., 1500.)
vox_plot.pixels = (200, 200, 200)
vox_plot.color_by = 'cell'
openmc.plot_geometry()
os.system('openmc-voxel-to-vtk plot_12.h5 -o test_voxel_plot.vti')
```
after this PR
```
import openmc
surf1 = openmc.Sphere(r=500, boundary_type='vacuum')
cell1 = openmc.Cell(region=-surf1)
geometry = openmc.Geometry([cell1])
geometry.export_to_xml()
materials = openmc.Materials()
materials.export_to_xml()
vox_plot = openmc.Plot()
vox_plot.type = 'voxel'
vox_plot.id = 12
vox_plot.width = (1500., 1500., 1500.)
vox_plot.pixels = (200, 200, 200)
vox_plot.color_by = 'cell'
vox_plot.to_voxel_file(output='test_voxel_plot.vti')
```
closes #2219

2023-04-26 17:36 UTC, paulromano requested changes
Thanks for moving this code over to the proper API @shimwell. I spruced it up a bit and sent a PR to your fork: https://github.com/shimwell/openmc/pull/29

2023-04-26 18:09 UTC, paulromano requested changes
Oops, forgot some `versionadded` directives and noticed we needed an update in the script

2023-04-26 18:09 UTC, paulromano commented on openmc/plots.py
> +    Parameters
```suggestion
    """Converts a voxel HDF5 file to a VTK file

    .. versionadded:: 0.13.4

    Parameters
```

2023-04-26 18:09 UTC, paulromano commented on openmc/plots.py
> +        Parameters
```suggestion
        This method runs OpenMC in plotting mode to produce a .vti file.

        .. versionadded:: 0.13.4

        Parameters
```

2023-04-26 18:09 UTC, paulromano commented on scripts/openmc-voxel-to-vtk
> +    openmc.plots._voxel_to_vtk(args.voxel_file, args.output)
```suggestion
    openmc.voxel_to_vtk(args.voxel_file, args.output)
```

2023-04-26 20:42 UTC, paulromano approved these changes

2023-04-27 14:36 UTC, merged

2023-04-29 21:00 UTC, shimwell commented
If anyone is interested in an example of this feature I just made one over [here](https://github.com/firstlightfusion/neutronics-workshop/blob/main/tasks/task_03_making_CSG_geometry/3_viewing_the_geometry_in_3d.ipynb)