added type hinting for weight_windows.py
openmc-dev/openmc pull request #2467
Opened 2023-04-12 18:03 UTC by christinacai123

2023-04-13 08:31 UTC, shimwell commented on openmc/weight_windows.py
> +    a simulation. Multiple sets of weight windows can be defined for differen  t
```suggestion
    a simulation. Multiple sets of weight windows can be defined for different
```
looks like a some spaces got added here

2023-04-13 21:27 UTC, christinacai123 reviewed
fixed spacing on line 23

2023-04-13 23:13 UTC, paulromano requested changes

2023-04-13 23:13 UTC, paulromano commented on openmc/weight_windows.py
> +        lower_ww_bounds: np.ndarray,
```suggestion
        lower_ww_bounds: Iterable[float],
```

2023-04-13 23:13 UTC, paulromano commented on openmc/weight_windows.py
> +        upper_ww_bounds: Optional[np.ndarray] = None,
```suggestion
        upper_ww_bounds: Optional[Iterable[float]] = None,
```

2023-04-13 23:13 UTC, paulromano commented on openmc/weight_windows.py
> +    def energy_bounds(self, bounds: Iterable[Real]):
```suggestion
    def energy_bounds(self, bounds: Iterable[float]):
```

2023-04-13 23:13 UTC, paulromano commented on openmc/weight_windows.py
> +    def upper_ww_bounds(self, bounds: Iterable[Real]):
```suggestion
    def upper_ww_bounds(self, bounds: Iterable[float]):
```

2023-04-13 23:13 UTC, paulromano commented on openmc/weight_windows.py
> +from typing import Iterable, List, Optional, Union
```suggestion
from typing import Iterable, List, Optional, Union, Dict
```

2023-04-13 23:13 UTC, paulromano commented on openmc/weight_windows.py
> +    def from_hdf5(cls, group: h5py.Group, meshes: dict) -> WeightWindows:
```suggestion
    def from_hdf5(cls, group: h5py.Group, meshes: Dict[int, MeshBase]) -> WeightWindows:
```

2023-04-13 23:13 UTC, paulromano commented on openmc/weight_windows.py
> +def wwinp_to_wws(path: Union[str, pathlib.Path]) -> List[WeightWindows]:
In the checkvalue.py module, we have an alias for this called `PathLike` that is used elsewhere

2023-04-15 19:45 UTC, christinacai123 reviewed
added suggested changes

2023-04-15 20:07 UTC, christinacai123 commented
We failed the one of the checks and were wondering if you had any advice on how to fix this?

2023-04-18 02:27 UTC, christinacai123 commented
Unfortunately, I am still failing the same check. Could you try retriggering the CI again?

2023-04-18 04:02 UTC, paulromano reviewed
Ah, it looks like you need to make a new commit on the branch for it to pick up updates from the `develop` branch in CI. I've just made a trivial suggestion that you can commit and hopefully that should do the trick.

2023-04-18 04:02 UTC, paulromano commented on openmc/weight_windows.py
> +import pathlib
```suggestion
import pathlib
import typing
from typing import Iterable, List, Optional, Union, Dict
```

2023-04-18 19:46 UTC, paulromano approved these changes

2023-04-19 01:35 UTC, merged