added return types for model.py
openmc-dev/openmc pull request #2468
Opened 2023-04-12 18:22 UTC by christinacai123

2023-04-12 19:12 UTC, christinacai123 reviewed
fixed circular import error

2023-04-13 23:02 UTC, paulromano requested changes

2023-04-13 23:02 UTC, paulromano commented on openmc/model/model.py
> +    def _cells_by_name(self) -> dict:
You can use typing.Dict to make this more specific
```suggestion
    def _cells_by_name(self) -> Dict[int, openmc.Cell]:
```

2023-04-13 23:02 UTC, paulromano commented on openmc/model/model.py
> +from typing import Optional
```suggestion
from typing import Optional, Dict
```

2023-04-13 23:02 UTC, paulromano commented on openmc/model/model.py
> +    def _materials_by_name(self) -> dict:
```suggestion
    def _materials_by_name(self) -> Dict[int, openmc.Material]:
```

2023-04-18 04:03 UTC, paulromano requested changes

2023-04-18 04:03 UTC, paulromano commented on openmc/model/model.py
> +
```suggestion

```

2023-04-18 19:46 UTC, paulromano approved these changes

2023-04-19 01:35 UTC, merged