more flexible cross section plotting
openmc-dev/openmc pull request #2478
Opened 2023-04-14 16:06 UTC by shimwell

As requested in issue #2476 this PR adds the ability to plot combinations of multiple nuclides, elements or materials with different cross section reactions.

Previously only one could only plot a single nuclide, element or material.

example script for multiple nuclides
```python
import openmc
import matplotlib.pyplot as plt
fig = openmc.plotter.plot_xs(
    this_and_types = {
        'Li6': [205],
        'Li7': [205],
        'Be9': [16, 205],
    }
)
plt.show()
```

example script for multiple materials
```python
import openmc
import matplotlib.pyplot as plt

mat1 = openmc.Material()
mat1.add_nuclide('Fe56', 1)
mat1.set_density('g/cm3', 1)

mat2 = openmc.Material()
mat2.add_element('Fe', 1)
mat2.add_nuclide('Fe55', 1)
mat2.set_density('g/cm3', 1)
mat2.name = 'Iron'

fig = openmc.plotter.plot_xs(
    this_and_types = {
        mat1: ['total'],
        mat2: ['elastic', 'total'],
    }
)
plt.show()

2023-04-14 17:59 UTC, shimwell commented
@aslakstubsgaard this PR would make multiple material plotting very easy which if I recall correctly you were quite keen on

2023-04-26 18:04 UTC, paulromano requested changes

2023-04-26 18:04 UTC, paulromano commented on openmc/plotter.py
> +    this_and_types : dict where keys are str or openmc.Material, values are Iterable of PLOT_TYPES
As long as we're changing the function signature (which I'm ok with -- I don't think this one gets a ton of usage at present), can we come up with a better name than `this_and_types`?

My only hesitance about the change (other than naming issues) is that this makes the simple case (single item/reaction) a bit more complex. But, the added functionality is probably worth it. :man_shrugging:

For documentation purposes, what comes after `:` here needs to be a proper type
```suggestion
    this_and_types : dict
```

2023-04-26 19:22 UTC, shimwell commented on openmc/plotter.py
> +        this = list(this_and_types.keys())[0]
I've never seen that particular way of unpacking return values before. I had to check it out and can confirm this is certainly magic

```python
>>> this_and_types = {'key1':'val1'}
>>> this = list(this_and_types.keys())[0]
>>> this
'key1'
>>> this, = this_and_types
>>> this
'key1'
```

2023-04-26 19:25 UTC, shimwell commented
TODO: think of a better arg name than ```this_and_types``` for the dictionary of objects to plot and the reactions to plot

2023-04-27 05:10 UTC, shimwell commented
> TODO: think of a better arg name than `this_and_types` for the dictionary of objects to plot and the reactions to plot

Perhaps we can use the old variable name ```this```

2023-04-27 12:19 UTC, paulromano commented
@shimwell How about `items`, which at least implies you can have multiple things by virtue of it being plural

2023-04-27 12:41 UTC, shimwell commented on openmc/plotter.py
> +def _get_yaxis_label(this_and_types, divisor_types):
```suggestion
def _get_yaxis_label(reactions, divisor_types):
```

2023-04-27 12:41 UTC, shimwell commented on openmc/plotter.py
> +    if all(isinstance(item, str) for item in this_and_types.keys()):
```suggestion
    if all(isinstance(item, str) for item in reactions.keys()):
```

2023-04-27 12:41 UTC, shimwell commented on openmc/plotter.py
> +    elif all(isinstance(item, openmc.Material) for item in this_and_types.keys()):
```suggestion
    elif all(isinstance(item, openmc.Material) for item in reactions.keys()):
```

2023-04-27 12:42 UTC, shimwell commented on openmc/plotter.py
> +def _get_title(this_and_types):
```suggestion
def _get_title(reactions):
```

2023-04-27 12:42 UTC, shimwell commented on openmc/plotter.py
> +        this, = this_and_types
```suggestion
        this, = reactions
```

2023-04-27 12:42 UTC, shimwell commented on openmc/plotter.py
> +def plot_xs(this_and_types, divisor_types=None, temperature=294., axis=None,
```suggestion
def plot_xs(reactions, divisor_types=None, temperature=294., axis=None,
```

2023-04-27 12:42 UTC, shimwell commented on openmc/plotter.py
> +    this_and_types : dict
```suggestion
    reactions : dict
```

2023-04-27 12:42 UTC, shimwell commented on openmc/plotter.py
> +    for this, types in this_and_types.items():
```suggestion
    for this, types in reactions.items():
```

2023-04-27 12:43 UTC, shimwell commented on openmc/plotter.py
> +    ax.set_title(_get_title(this_and_types))
```suggestion
    ax.set_title(_get_title(reactions))
```

2023-04-27 12:43 UTC, shimwell commented on tests/unit_tests/test_plotter.py
> +        this_and_types = {
```suggestion
        reactions = {
```

2023-04-27 12:43 UTC, shimwell commented on tests/unit_tests/test_plotter.py
> +        this_and_types = {
```suggestion
        reactions = {
```

2023-04-27 12:43 UTC, shimwell commented on tests/unit_tests/test_plotter.py
> +        this_and_types = {
```suggestion
        reactions = {
```

2023-04-27 12:44 UTC, shimwell commented on tests/unit_tests/test_plotter.py
> +                this_and_types = {
```suggestion
                reactions = {
```

2023-04-27 12:44 UTC, shimwell commented on tests/unit_tests/test_plotter.py
> +    title = openmc.plotter._get_title(this_and_types = {'Li': [205]})
```suggestion
    title = openmc.plotter._get_title(reactions = {'Li': [205]})
```

2023-04-27 12:44 UTC, shimwell commented on tests/unit_tests/test_plotter.py
> +    title = openmc.plotter._get_title(this_and_types = {mat1: [205]})
```suggestion
    title = openmc.plotter._get_title(reactions = {mat1: [205]})
```

2023-04-27 14:59 UTC, paulromano requested changes
A few little style nitpicks and then this should be good to merge. Thanks!

2023-04-27 14:59 UTC, paulromano commented on tests/unit_tests/test_plotter.py
> +    assert isinstance(openmc.plotter.plot_xs({this: ['total', 'elastic']}), Figure)
```suggestion
    assert isinstance(openmc.plot_xs({this: ['total', 'elastic']}), Figure)
```

2023-04-27 14:59 UTC, paulromano commented on tests/unit_tests/test_plotter.py
> +        reactions = {
```suggestion
        reactions={
```

2023-04-27 14:59 UTC, paulromano commented on tests/unit_tests/test_plotter.py
> +    title = openmc.plotter._get_title(reactions = {'Li': [205]})
```suggestion
    title = openmc.plotter._get_title(reactions={'Li': [205]})
```

2023-04-27 14:59 UTC, paulromano commented on tests/unit_tests/test_plotter.py
> +    title = openmc.plotter._get_title(reactions = {
```suggestion
    title = openmc.plotter._get_title(reactions={
```

2023-04-27 14:59 UTC, paulromano commented on tests/unit_tests/test_plotter.py
> +    title = openmc.plotter._get_title(reactions = {mat1: [205]})
```suggestion
    title = openmc.plotter._get_title(reactions={mat1: [205]})
```

2023-04-27 15:17 UTC, paulromano approved these changes

2023-04-28 03:26 UTC, merged