Provide alternative batch estimation message
openmc-dev/openmc pull request #2479
Opened 2023-04-15 02:24 UTC by pshriwise

Provides an alternative error message if the ratio between the tally uncertainty and threshold uncertainty is `INFTY`.

Resolves #2477.

2023-04-15 06:10 UTC, shimwell commented
Thanks Patrick, that was very quick, I'm keen to give this a go once I get back to my desktop on Monday.

2023-04-17 10:47 UTC, shimwell approved these changes
Thanks Patrick this does close out that issue nicely. Thanks for clearing that up

2023-04-17 10:48 UTC, shimwell commented
If there are no objections as this is a relatively small PR, I shall add that merging in < 24 hours tag and aim to merge this in tomorrow

2023-04-18 04:10 UTC, paulromano requested changes
Need clang-format on this one

2023-04-18 05:36 UTC, pshriwise commented
> Need clang-format on this one

Oops, sure does. Fresh OS install got me.

2023-04-18 11:27 UTC, paulromano approved these changes
Thanks!

2023-04-18 11:27 UTC, merged