Transfer rates mpi
openmc-dev/openmc pull request #2551
Opened 2023-06-07 08:50 UTC by church89

I realized `transfer_rates` did not run with MPI when coupling between materials is set and the block matrix is created. 
This PR temporarily addresses the issue by gathering all data into 1 process to solve the depletion block matrix, before broadcasting the results and distribute across all other processes. 
Later would be nice to have matrix decomposition across mpi processes (I can open an Issue for that).

2023-06-13 10:38 UTC, yardasol reviewed
Hi @church89,

I think I brought this up in the review for #2358, but there was so much discussion on this post it probably got buried, so I'm glad you are making a PR for this!

One concern I have with this implementation is it that is seems to be separating a bit too much the "normal" depletion matrix and the depletion matrix formed when using transfer rates. Why is the existing MPI functionality (using `pool.starmap()`) in the depletion module not sufficient?

2023-06-13 15:25 UTC, church89 commented
Hi @yardasol,

This PR concerns the block matrix that turns out only when a `destination_material` is defined in the `add_transfer_rate` method. 
As it is now, the code breaks when running with mpi and more than 1 process, since the matrices composing the block matrix are spread across the different mpi processes.
This PR addresses it by gathering all in one process and broadcasting back to the others after having solved the matrix.

2023-06-14 14:37 UTC, paulromano requested changes
Thanks for the PR @church89! Just a few small requests on this:

2023-06-14 14:37 UTC, paulromano commented on openmc/deplete/pool.py
> +            x = comm.gather(x, root=0)
Default root is 0, so the second argument can be omitted
```suggestion
            matrices = comm.gather(matrices)
            x = comm.gather(x)
```

2023-06-14 14:37 UTC, paulromano commented on openmc/deplete/pool.py
> +                matrices = [elm for matrice in matrices for elm in matrice]
```suggestion
                matrices = [elm for matrix in matrices for elm in matrix]
```

2023-06-16 04:00 UTC, paulromano approved these changes

2023-06-16 04:00 UTC, merged