Add C++ format check to GitHub Actions
openmc-dev/openmc pull request #2554
Opened 2023-06-08 16:49 UTC by pshriwise

As perhaps the most frequent perpetrator in attempting to violate our C++ format guidelines these days, I thought I'd invest a little of my time to save a lot of others' by adding an automated formatting check in our actions for pull requests. Using a consistent environment and `clang-format` version also allows us to ensure that the code formatting check is consistent.

This PR adds a workflow using the https://github.com/cpp-linter/cpp-linter-action to check any of the changed `.cpp`/`.h` files in the PR for proper formatting. The action provides file annotations in the code changes highlighting the offending lines as well as a summary of the format check in the job summary. It can also provide a summary of the violating files in the PR thread. I think this would be the fastest and most visible way for submitters/reviewers to check the formatting result, but I found that after fixing the formatting the thread comment doesn't always update correctly. For a technical explanation of why this is, see [here](https://github.com/cpp-linter/cpp-linter-action/issues/154). At the same time, it might be preferable to keep the PR thread comments to discussion of design/code only without extra clutter. 🤷🏻 

FWIW, there are many tools out there that perform this kind of operation but this tool I found to be well-supported and actively maintained (as evidenced by the fast response to the issue I raised) with all of the features I was looking for (formatting chcek only changed files, per-file annotations, optional failure if formatting is needed).

On that last note, I currently have this action setup to pass but add file annotations if the format is violated. It's would be very easy to report failure from the job and still add file annotations to block a PR merge with format violations.

2023-06-08 16:55 UTC, pshriwise commented
Adding a poorly-formatted function to a file to demonstrate temporarily...

2023-06-14 14:51 UTC, paulromano requested changes
I guess this PR atones for all your C++ format sins :angel: Thanks for putting this together! My only request is that the C++ format check should fail to make it a little more visible. We can make it separate decision whether that status check should be required for merging (IMO, it should to prevent future PRs from having changed lines simply due to running clang-format).

Also, just to make sure I understand — if a file fails a format check, we will just get a single comment saying it is not formatted correctly, right? (that is what I'd want)

2023-06-15 13:36 UTC, pshriwise commented
Redemption!! 🙌🏻 

Sounds good. I'll set the check to produce a failure in the action. Based on our repo settings, this failure will prevent PRs from being merged until `clang-format` is applied. I don't know of a way to produce an "allowed failure" in GHA despite several searches. The best option I know of is the [`continue-on-error` option](https://github.com/actions/runner/issues/2347), but that won't produce an easy status check in the PR summary.

Comments are what I'd prefer too! But sadly no. What we get is an annotation at the top of each file in the "Files changed" tab and a set of files violating the style guide in the GHA job summary. While testing this capability in my fork I found that comments don't always update reliably with new commits, potentially leading to confusion about whether or not the files are properly formatted. My conversation about this with the tool maintainer is [here](https://github.com/cpp-linter/cpp-linter-action/issues/154).

2023-06-15 13:41 UTC, pshriwise commented
FWIW, one thing that would be nice to add in the future is a GHA bot that will apply `clang-fromat` if triggered by a PR comment. These changes provide assurance that our style is consistent (always same `clang-format` version and checks all lines changed going into the `develop` branch), but it doesn't make it easier for contributors to apply `clang-format` in a way that is consistent  with the GHA checks.

2023-06-15 16:13 UTC, pshriwise commented
For posterity here's the summary from a [failed check](https://github.com/openmc-dev/openmc/actions/runs/5280136003/jobs/9551806948?pr=2554 ) on commit https://github.com/openmc-dev/openmc/pull/2554/commits/3c654cf10009c2b77a344de09f5564049c0008d7 in this PR: https://github.com/openmc-dev/openmc/actions/runs/5280136003?pr=2554

2023-06-16 04:03 UTC, paulromano approved these changes

2023-06-16 04:03 UTC, merged