Static errors continuation
openmc-dev/openmc pull request #2557
Opened 2023-06-09 09:46 UTC by shimwell

Following up on PR #2485 which did a lot of the ground work needed to get mypi running.

I didn't want the 1000 lines of changes already done in #2485 to go to waste and I am keen on seeing more python checking (mypi, flake8, black etc) being made use of in openmc so I am keen to finish this mypi PR

2023-06-09 13:07 UTC, shimwell commented
This PR attracts merge conflicts like a they are magnetic. One just arrived in tallies.py today and there was one yesterday

2023-06-16 20:34 UTC, paulromano requested changes
Thanks for continuing work on this @shimwell  -- there are a few small things that need fixing but should be good to merge after that.

2023-06-16 20:34 UTC, paulromano commented on openmc/data/energy_distribution.py
>  class DiscretePhoton(EnergyDistribution):
There should be two lines before a class definition per PEP8
```suggestion

class DiscretePhoton(EnergyDistribution):
```

2023-06-16 20:34 UTC, paulromano commented on openmc/geometry.py
> +        return self._surface_precision
```suggestion
    @property
    def surface_precision(self) -> int:
        return self._surface_precision
```

2023-06-16 20:34 UTC, paulromano commented on openmc/mgxs/mgxs.py
> +
```suggestion
```

2023-06-17 03:34 UTC, paulromano approved these changes

2023-06-17 03:34 UTC, merged