Option units for geometry plot
openmc-dev/openmc pull request #2575
Opened 2023-06-22 15:35 UTC by shimwell

# Description

It would be handy for people with large models to be able to plot geometry with different units. The default is still cm so this won't break anything for existing scripts. I have a few models where meters would be ideal so I would just add ```axis_units='m'``` to the arguments. Is there any chance we can allow axis units on the ```universe.plot```?

Fixes # (issue)
No issue sorry

# Checklist

- [x] I have performed a self-review of my own code
- [x] I have run [clang-format](https://docs.openmc.org/en/latest/devguide/styleguide.html#automatic-formatting) on any C++ source files (if applicable)
- [x] I have followed the [style guidelines](https://docs.openmc.org/en/latest/devguide/styleguide.html#python) for Python source files (if applicable)
- [x] I have made corresponding changes to the documentation (if applicable)
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)

2023-06-22 16:00 UTC, makeclean commented
would you also expect when plotting meshes on said geometry the flux to renomalise to m^2 or not?

On Jun 22 2023, at 4:35 pm, Jonathan Shimwell ***@***.***> wrote:
> Description
> It would be handy for people with large models to be able to plot geometry with different units to the default cm. For example I have a few models where meters would be idea. Is there any chance we can allow axis units on the universe.plot
>
> Fixes # (issue)
> No issue sorry
>
>
> Checklist
> I have performed a self-review of my own code
>
> I have run clang-format (https://docs.openmc.org/en/latest/devguide/styleguide.html#automatic-formatting) on any C++ source files (if applicable)
>
> I have followed the style guidelines (https://docs.openmc.org/en/latest/devguide/styleguide.html#python) for Python source files (if applicable)
>
> I have made corresponding changes to the documentation (if applicable)
>
> I have added tests that prove my fix is effective or that my feature works (if applicable)
>
>
> You can view, comment on, or merge this pull request online at:
> https://github.com/openmc-dev/openmc/pull/2575
>
> Commit Summary
> 79a5302 (https://github.com/openmc-dev/openmc/pull/2575/commits/79a5302945e4a70c803d2e34c6948411b4f28199) geometry plots in mm, cm, m, km
>
> 7f1678d (https://github.com/openmc-dev/openmc/pull/2575/commits/7f1678d24222259868a16a2529bbb6065cc33ceb) added doc string for axis_units
>
>
> File Changes
> (1 file (https://github.com/openmc-dev/openmc/pull/2575/files))
>
> M openmc/universe.py (https://github.com/openmc-dev/openmc/pull/2575/files#diff-a36af801338f90369cff49559fb0943fb1135e0a7c9e9c935b7de7514138f5bd) (22)
> Patch Links:
> https://github.com/openmc-dev/openmc/pull/2575.patch
>
> https://github.com/openmc-dev/openmc/pull/2575.diff
>
>
> —
> Reply to this email directly, view it on GitHub (https://github.com/openmc-dev/openmc/pull/2575), or unsubscribe (https://github.com/notifications/unsubscribe-auth/AASTUSV3MS2ASMTEY5OQVYTXMRQ5TANCNFSM6AAAAAAZQMPGIQ).
> You are receiving this because you are subscribed to this thread.
>

2023-06-22 16:42 UTC, shimwell commented
tests appear to be failing on np.product which has changed to np.prod. There is a PR in for fixing that already so I think that is unrelated to this PR

2023-06-22 21:56 UTC, paulromano requested changes
Thanks for this improvement @shimwell! Pushing another commit here should resolve the test failures

2023-06-22 21:56 UTC, paulromano commented on openmc/universe.py
> +            Units used on the plot axis, the default is cm
No need to mention default since it is in the method signature
```suggestion
            Units used on the plot axis
```

2023-06-23 02:43 UTC, paulromano approved these changes

2023-06-24 17:38 UTC, shimwell commented
Thanks Paul, tests are passing again now.

2023-06-24 23:03 UTC, merged