Change "update_params" to "update_parameters" in test suite: test_ww_gen.py
openmc-dev/openmc pull request #2577
Opened 2023-06-23 17:19 UTC by j-fletcher

On line 232 of test_ww_gen.py, an "update_params" variable associated with the weight window generator is set, whereas an "update_parameters" variable is expected according to the openmc.WeightWindowGenerator documentation. In this branch I have corrected the variable name such that the ratio, threshold, and value may be specified.

# Checklist

- [x] I have performed a self-review of my own code

2023-06-23 20:03 UTC, pshriwise approved these changes
Thanks for catching this @j-fletcher!

2023-06-23 20:14 UTC, eepeterson requested changes

2023-06-23 20:14 UTC, eepeterson commented on tests/unit_tests/weightwindows/test_ww_gen.py
> +                            'value' : 'mean'}
I think these two lines should be indented one space more and the tab or white space in front removed, thanks for the fix!

2023-06-23 20:17 UTC, eepeterson commented on tests/unit_tests/weightwindows/test_ww_gen.py
> +                            'value' : 'mean'}
You should be able to set your text editor to convert tabs to 4 spaces for python files and [PEP 8](https://peps.python.org/pep-0008/#tabs-or-spaces) suggests to use spaces instead.

2023-06-27 23:22 UTC, eepeterson commented on tests/unit_tests/weightwindows/test_ww_gen.py
> +                            'value' : 'mean'}
```suggestion
                             'threshold': 0.8,
                             'value' : 'mean'}
```

2023-06-28 22:57 UTC, merged