Cylindrical bb
openmc-dev/openmc pull request #2621
Opened 2023-07-23 16:01 UTC by caderache2014

# Description
Very similar changes to the changes in #2620. Add bounding box, upper_right, and lower_left properties to CylindricalMesh class. Added a unit test.
# Checklist

- [x] I have performed a self-review of my own code
- [x] I have run [clang-format](https://docs.openmc.org/en/latest/devguide/styleguide.html#automatic-formatting) on any C++ source files (if applicable)
- [x] I have followed the [style guidelines](https://docs.openmc.org/en/latest/devguide/styleguide.html#python) for Python source files (if applicable)
- [x] I have made corresponding changes to the documentation (if applicable)
- [x] I have added tests that prove my fix is effective or that my feature works (if applicable)

2023-07-23 16:59 UTC, shimwell commented on tests/unit_tests/test_mesh.py
> +    mesh = openmc.ClyindricalMesh()
```suggestion
    mesh = openmc.CylindricalMesh()
```

2023-07-23 17:12 UTC, caderache2014 commented
@shimwell  yes I did notice the misspelling. I shouldn't have any problems running the unit tests locally in the future

2023-07-25 07:53 UTC, shimwell commented on openmc/mesh.py
> +        are given, it is assumed that the mesh is an x-y mesh.
```suggestion
        The lower-left corner of the structured mesh.
```
I think this doc string can be shortened as the last sentence applies to regularmesh but perhaps not cylindrical mesh

2023-07-25 07:53 UTC, shimwell commented on openmc/mesh.py
> +        are given, it is assumed that the mesh is an x-y mesh.
```suggestion
        The upper-right corner of the structured mesh.
```
also this doc string, same as above

2023-07-25 07:54 UTC, shimwell commented on tests/unit_tests/test_mesh.py
> +
```suggestion
```

2023-07-25 08:07 UTC, shimwell commented on tests/unit_tests/test_mesh.py
> +    np.testing.assert_array_equal(bb.upper_right, np.array([4, 6, 8]))
```suggestion
    np.testing.assert_array_equal(bb.upper_right, np.array([4, 6, 8]))

```

2023-07-28 15:56 UTC, paulromano requested changes

2023-07-28 15:56 UTC, paulromano commented on openmc/mesh.py
> +            raise ValueError("Mesh cannot have zero thickness in any dimension")
Same story here as in PR #2620. The setters should be unnecessary since these properties are computed based on other attributes.

2023-08-03 17:39 UTC, caderache2014 commented
@shimwell can you tell if this test failed due to something beyond the remit of my changes?
![image](https://github.com/openmc-dev/openmc/assets/3958502/e23d168f-b756-4d7b-9c80-be06b15f93c4)

2023-08-03 18:30 UTC, shimwell commented
> @shimwell can you tell if this test failed due to something beyond the remit of my changes? ![image](https://user-images.githubusercontent.com/3958502/258191936-e23d168f-b756-4d7b-9c80-be06b15f93c4.png)

You are right, this CI error is beyond the remit of this PR. It looks like the nuclear data download is failing. Nothing for you to worry about. I can rerun the CI tomorrow and see if the download is working again

2023-08-06 06:23 UTC, paulromano approved these changes

2023-08-06 08:27 UTC, caderache2014 commented
@paulromano Cool! Thanks Dr Romano!

2023-08-06 09:26 UTC, merged