Add RectangularPrism and HexagonalPrism composite surfaces
openmc-dev/openmc pull request #2739
Opened 2023-10-19 21:12 UTC by paulromano

# Description

One thing in our Python API that has always been confusing to users is the `rectangular_prism` and `hexagonal_prism` functions. As opposed to surfaces (where you need to take `-` or `+` to get a proper region that can be assigned to a cell), these functions return `Region` objects directly, so you can't do:
```Python
prism = openmc.model.rectangular_prism(...)
cell = openmc.Cell(region=-prism)  # The '-' operator doesn't work!
```

This PR proposes two new classes, `RectangularPrism` and `HexagonalPrism`, that are meant to replace those two functions are give us composite surfaces that work with the unary `-` and `+` operators.

# Checklist

- [x] I have performed a self-review of my own code
- [x] <s>I have run [clang-format](https://docs.openmc.org/en/latest/devguide/styleguide.html#automatic-formatting) on any C++ source files (if applicable)</s>
- [x] I have followed the [style guidelines](https://docs.openmc.org/en/latest/devguide/styleguide.html#python) for Python source files (if applicable)
- [x] I have made corresponding changes to the documentation (if applicable)
- [x] I have added tests that prove my fix is effective or that my feature works (if applicable)

2023-10-20 21:34 UTC, paulromano commented
Making a note to myself that this will need to be updated if #2724 is merged first.

2023-10-31 22:20 UTC, pshriwise requested changes
One tiny suggestion but I think this looks good otherwise @paulromano. Thanks!!

2023-10-31 22:20 UTC, pshriwise commented on tests/regression_tests/periodic_hex/test.py
> +    cell = openmc.Cell(fill=fuel, region=-hex_region)
```suggestion
    hex_prism = openmc.model.HexagonalPrism(10.0, boundary_type='periodic')
    cell = openmc.Cell(fill=fuel, region=-hex_prism)
```

2023-10-31 22:42 UTC, paulromano commented
Thanks @pshriwise. Just incorporated your suggestion and also resolved a merge conflict.

2023-11-01 14:04 UTC, pshriwise approved these changes

2023-11-01 14:13 UTC, merged