Adding get cylindrical mesh index at specified coordinates
openmc-dev/openmc pull request #2782
Opened 2023-11-20 17:35 UTC by shimwell

# Description

This PR attempts to add the ability to get the cylindrical mesh index of a x,y,z coordinate. This is useful when users are trying to find the mesh value at a specific location.

usage is ...
```python
openmc.CylindricalMesh(r_grid=(0, 5, 10), z_grid=(0, 5, 10))
r, phi, z = mesh.get_indices_at_coords(1, 0, 1)
```

Fixes # (issue)

# Checklist

- [x] I have performed a self-review of my own code
- [x] I have followed the [style guidelines](https://docs.openmc.org/en/latest/devguide/styleguide.html#python) for Python source files (if applicable)
- [x] I have made corresponding changes to the documentation (if applicable)
- [x] I have added tests that prove my fix is effective or that my feature works (if applicable)

2023-11-28 16:52 UTC, paulromano requested changes
Looks like a nice addition, thanks @shimwell! A few comments below:

2023-11-28 16:52 UTC, paulromano commented on openmc/mesh.py
> +        r_index = np.argmax(r_grid_values > r_value_from_origin) - 1
`np.searchsorted` would be more appropriate than `np.argmax`, and should in theory be faster

2023-11-29 11:19 UTC, shimwell commented
Thanks for the review @paulromano 

I have gone through and I believe I've addressed all the review comments and adopted all suggestions.

2023-12-12 19:29 UTC, paulromano approved these changes

2023-12-12 19:29 UTC, merged