Clarifying documentation for Cones
openmc-dev/openmc pull request #2892
Opened 2024-03-04 23:55 UTC by MicahGale

# Description

This provides some clarification on how `Cone` surfaces are formed, to address some user confusion that occured. 

Fixes #2981.

# Checklist

- [ ] I have performed a self-review of my own code
- [ ] ~I have run [clang-format](https://docs.openmc.org/en/latest/devguide/styleguide.html#automatic-formatting) (version 15) on any C++ source files (if applicable)~
- [ ] I have followed the [style guidelines](https://docs.openmc.org/en/latest/devguide/styleguide.html#python) for Python source files (if applicable)
- [x] I have made corresponding changes to the documentation (if applicable)
- [ ] ~I have added tests that prove my fix is effective or that my feature works (if applicable)~

2024-03-06 17:03 UTC, gridley requested changes

2024-03-06 17:03 UTC, gridley commented on openmc/surface.py
> +        This is the square of the radius of the cone 1 cm from.
Incorrect use of square brackets for units:

https://hsm.stackexchange.com/questions/5907/old-square-bracket-notation-for-units

2024-03-06 17:03 UTC, gridley commented on openmc/surface.py
> +        For a "traditional" cone see :class:`~openmc.model.XConeSided`.
https://hsm.stackexchange.com/questions/5907/old-square-bracket-notation-for-units

2024-03-06 20:20 UTC, MicahGale commented on openmc/surface.py
> +        For a "traditional" cone see :class:`~openmc.model.XConeSided`.
@gridley how is this relevant to these lines?

2024-03-06 20:32 UTC, MicahGale commented on openmc/surface.py
> +        This is the square of the radius of the cone 1 cm from.
Square brackets are used throughout the documentation for units, and is beyond the scope of this PR. 

In general I disagree with your sentiment about this notation. Also "Only the Sith deal in absolutes".

2024-03-06 22:27 UTC, pshriwise requested changes
Some class name corrections and a typo fix to tackle but then I think this looks good!

2024-03-06 22:27 UTC, pshriwise commented on openmc/surface.py
> +        For a one-sided cone see :class:`~openmc.model.ZConeSided`.
```suggestion
        For a one-sided cone see :class:`~openmc.model.ZConeOneSided`.
```

2024-03-06 22:27 UTC, pshriwise commented on openmc/surface.py
> +        For a one-sided cone see :class:`~openmc.model.YConeSided`.
```suggestion
        For a one-sided cone see :class:`~openmc.model.YConeOneSided`.
```

2024-03-06 22:27 UTC, pshriwise commented on openmc/surface.py
> +        For a one-sided cone see :class:`~openmc.model.XConeSided`.
```suggestion
        For a one-sided cone see :class:`~openmc.model.XConeOneSided`.
```

2024-03-06 22:27 UTC, pshriwise commented on openmc/surface.py
> +        For a one-sided cone see :class:`~openmc.model.XConeSided`,
```suggestion
        For a one-sided cone see :class:`~openmc.model.XConeOneSided`,
```

2024-03-06 22:27 UTC, pshriwise commented on openmc/surface.py
> +        This creates a double cone, which is two one-sides cones that meet at their apex.
```suggestion
        This creates a double cone, which is two one-sided cones that meet at their apex.
```

2024-03-06 23:20 UTC, MicahGale commented on openmc/surface.py
> +        For a "traditional" cone see :class:`~openmc.model.XConeSided`.
Corrected all class names, and verified that the link is correct.

2024-03-06 23:26 UTC, MicahGale commented
I came across this documentation:

> A one-sided cone is composed of a normal cone surface and an “ambiguity” surface that eliminates the ambiguity as to which region of space is included. This class acts as a proper surface, meaning that unary + and - operators applied to it will produce a half-space. The negative side is defined to be the region inside of the cone.

I feel like "ambiguity" surface here is a bit counterintuitive. Would "disambiguation" surface be better?

2024-03-07 02:15 UTC, pshriwise commented
> I came across this documentation:
> 
> > A one-sided cone is composed of a normal cone surface and an “ambiguity” surface that eliminates the ambiguity as to which region of space is included. This class acts as a proper surface, meaning that unary + and - operators applied to it will produce a half-space. The negative side is defined to be the region inside of the cone.
> 
> I feel like "ambiguity" surface here is a bit counterintuitive. Would "disambiguation" surface be better?

Based on the purpose described here, I would agree.

2024-03-07 23:14 UTC, pshriwise approved these changes
Thanks @MicahGale!

2024-03-09 18:49 UTC, gridley approved these changes
LGTM @MicahGale!

2024-03-09 18:49 UTC, merged