Add MG particle speed getter and delayed fission neutron emission
openmc-dev/openmc pull request #2898
Opened 2024-03-08 16:16 UTC by ilhamv

# Description

Add MG particle speed getter and delayed fission neutron emission. This extends OpenMC's capability to run autonomous problems accurately, such as neutron pulse experiments.

Input for `settings.max_secondaries` is added with the default (originally hard-coded) value of 10000. This allows users to set up buffers to run near-critical or super-critical time-dependent problems (accompanied by `time_cutoff`, of course).

Fixes #2885 

# Checklist

- [ ] I have performed a self-review of my own code
- [x] I have run [clang-format](https://docs.openmc.org/en/latest/devguide/styleguide.html#automatic-formatting) (version 15) on any C++ source files (if applicable)
- [x] I have followed the [style guidelines](https://docs.openmc.org/en/latest/devguide/styleguide.html#python) for Python source files (if applicable)
- [x] I have made corresponding changes to the documentation (if applicable)
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)

# Verification

## MG test
Here is the result of a pulsed infinite homogeneous 361-group problem, where the MGXS is generated from the `pincell` example:

![shem361](https://github.com/openmc-dev/openmc/assets/26186244/afb9ca44-563e-40bf-892b-a9fb1b5e21db)

The "analytical" reference solution is also shown for verification. The simulation was run in 10 batches with 100k particles per batch. 

## CE test
Here is the result of the `jezebel` example pulsed with 2 MeV isotropic point source at the origin:

![jez_n](https://github.com/openmc-dev/openmc/assets/26186244/641edce9-3bc8-455a-85d4-ab72ec6fc938)

The simulation was run in 10 batches with 100k particles per batch. 

Estimates of neutron inverse period, or time constant $\alpha$, can be naively calculated from two consecutive data points:

![jez_alpha](https://github.com/openmc-dev/openmc/assets/26186244/31ccaa7a-5225-490c-9e7d-e51b865461c9)

Experimental value for the prompt neutron time constant ($\alpha_p$ = -640 +- 10 /ms) is also shown above for verification.

Note: In running this Jezebel problem, I had to increase the secondary bank size limit from the default value 10k to 100k.

2024-03-08 16:26 UTC, ilhamv commented
The additional step of sampling delayed emission time shifts the random number sequence used in the rest of the random walk, which would make some (if not most) of the regression tests fail.

Is revising the regression test keys an option?

If not, the solution would be to only perform the delayed time sampling if a time-dependent problem is run (i.e., if `TimeFilter` is used in at least one tally).

2024-03-10 16:29 UTC, gridley commented
Thanks @ilhamv! I believe that we should be consuming that extra random number to sample the delayed group emission time, so I'm going to tie @paulromano into this to put it on his radar. I think typically, in the past, people have let a few proposed changes accrue before changing the RNG stream. At that point some statistical equivalence testing is done between the two versions, and all the tests get updated.

If we're tracking particle times during normal simulation, the delayed emission times should not be incorrect, IMO. Correctness should not be an option--this was the same principle that guided the decision of having resonance upscattering turned _on_ by default, in contrast to most other CE MC codes.

2024-03-10 16:44 UTC, gridley requested changes
I am only requesting a change on a typo which was already there but is in a line that you modified; other than that it all looks good to me. Going to wait on @paulromano for his thoughts on updating the tests.

2024-03-10 16:44 UTC, gridley commented on docs/source/methods/neutron_physics.rst
> +:math:`\nu_d`. Once these have been determined, we can calculated the delayed
```suggestion
:math:`\nu_d`. Once these have been determined, we can calculate the delayed
```

I know it's not your typo, but might as well fix it while we're here.

2024-03-10 16:44 UTC, gridley commented on src/particle.cpp
>      hit_time_boundary = true;
Just realized that the time cutoffs will work just fine for running transients, we just need to add some banking logic here if the boundary is less than the time cutoff. yay!

2024-03-10 16:44 UTC, gridley commented on src/physics.cpp
> +      if (p.secondary_bank().size() >= settings::max_secondaries) {
Very nice, we needed this change! Hardcoded values 🤢

2024-03-10 16:46 UTC, gridley commented
By the way, I think the code here to simulate the transient pulse would be worth including in the examples section. Would you want to include it as part of this PR?

2024-03-11 16:22 UTC, ilhamv commented
> If we're tracking particle times during normal simulation, the delayed emission times should not be incorrect, IMO. Correctness should not be an option that's off by default--this was the same principle that guided the decision of having resonance upscattering turned _on_ by default, in contrast to most other CE MC codes.

I really like that principle. 👍🏽 

> By the way, I think the code here to simulate the transient pulse would be worth including in the examples section. Would you want to include it as part of this PR?

Sure, I'll add the example as part of this PR.
Thanks, @gridley!

2024-04-03 17:15 UTC, ilhamv commented
There was a little bug in the use of MG_mode + collision estimator + survival_biasing: https://github.com/openmc-dev/openmc/pull/2898/commits/6ca1ae09547dd78684b31a1bfe155d6eed141b2b

@gridley @nelsonag 

(Note: had to use the collision estimator due to the current limitation of MeshFilter + TimeFilter).

2024-04-24 17:14 UTC, paulromano reviewed
@ilhamv Thanks for this PR and please accept my apologies that I haven't gotten around to properly reviewing it until now. I just made a few cosmetic updates on your branch and also took care of a merge conflict.

As @gridley pointed out, the additional random number that is sampled here for the delayed neutron time will cause the overall stream of random numbers to be different, which will fail most if not all of our regression tests. However, the guiding principle that @gridley put to words is indeed one of our tenets for OpenMC:
> Correctness should not be an option that's off by default

So, if we really need to update our regression test results in the name of correctness, so be it. However, first I'll ask whether there are other changes you have in mind that would also result in more random number stream changes, in which case we might want to group them together as we've done previously.

2024-04-24 21:27 UTC, gridley commented
Paul, that's great to hear, because I have had this other change on my radar to change the random number stream. We assume target nuclei are stationary above a certain energy threshold, and there's this recent paper that shows it introduces some non-negligible error for systems with finely distributed resonant material like TRISO or cracked MSR moderator.

The asymptotic form of the target velocity should just be to sample directly from Maxwell-Boltzmann, i.e. x y and z velocities are normally distributed. We should fall back to that rather than stationarity. The authors said it's like a 6% slowdown by always sampling the target motion.

https://arxiv.org/abs/2403.14486

2024-04-24 22:13 UTC, paulromano commented
Ah yes, thanks for bringing that up @gridley. I did talk to the authors of that paper so I'm aware of the issue at hand.

2024-04-27 17:33 UTC, ilhamv commented
No problem, @paulromano. Thanks!

I think that is the only change needed in the random number stream for analog time-dependent simulations. Unless there are other reactions that produce delayed particles (neutron/photon)..?

Some other items that I want to bring up for consideration (not directly related to this PR, though):
- To get the track-length estimator working properly for tallying with both time and mesh filters, would it make sense to make the mesh filter 4D (x,y,z,t)?
- Currently, the weight cutoff can not be set to zero. However, I see that in certain time-dependent problems where the neutron population decreases significantly in time, we do want to set the weight cutoff to zero (no cutoff) and instead set the time cutoff to a time range of interest. Would it be a good idea to allow users to do that? If it is a good idea, I can push a commit where I just removed the last argument in `cv.check_greater_than('weight cutoff', cutoff[key], 0.0, True)`.

2025-09-12 19:05 UTC, paulromano commented
@ilhamv I just made some updates on this branch and resolved conflicts. As far as I'm concerned, it's good to go (pending test result updates). I'm going to look at #2992 now and once that's in good shape, I'll go ahead and combine them and generate updated regression test results.

2025-09-17 14:55 UTC, paulromano commented
@ilhamv FYI after merging the develop branch, I found that I needed to revert a change you made for when `parent_id` and `progeny_id` are written; the problem was that the change you made resulted in those properties not being transferred to the fission bank.

2025-09-17 23:35 UTC, ilhamv commented
> @ilhamv FYI after merging the develop branch, I found that I needed to revert a change you made for when `parent_id` and `progeny_id` are written; the problem was that the change you made resulted in those properties not being transferred to the fission bank.

Ah, I see, should've assigned the IDs before banking the site... 😓 Sorry about that!
Thanks, Paul!

2025-09-19 13:41 UTC, closed without merging

2025-09-19 13:41 UTC, paulromano commented
Merged as part of #2992 :tada: