Changed CI to use latest actions to get away from the Node 16 deprecation.
openmc-dev/openmc pull request #2912
Opened 2024-03-12 13:16 UTC by MicahGale

# Description

Please include a summary of the change and which issue is fixed if applicable. Please also include relevant motivation and context.

Fixes # (issue)

# Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have run [clang-format](https://docs.openmc.org/en/latest/devguide/styleguide.html#automatic-formatting) (version 15) on any C++ source files (if applicable)
- [ ] I have followed the [style guidelines](https://docs.openmc.org/en/latest/devguide/styleguide.html#python) for Python source files (if applicable)
- [ ] I have made corresponding changes to the documentation (if applicable)
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)

2024-03-12 14:47 UTC, paulromano requested changes

2024-03-12 14:47 UTC, paulromano commented on .github/workflows/dockerhub-publish-dev.yml
> +        uses: docker/build-push-action@v5.2.0
This should be sufficient since the `v5` tag points to `v5.2.0`
```suggestion
        uses: docker/build-push-action@v5
```

2024-03-12 14:47 UTC, paulromano commented on .github/workflows/dockerhub-publish-dev.yml
> +        uses: docker/setup-buildx-action@v3.1
```suggestion
        uses: docker/setup-buildx-action@v3
```

2024-03-12 18:38 UTC, paulromano commented
> Another question: do we just pin to `@master`?

I'm personally fine sticking with our current mode of operation. The major updates to these actions don't seem to happen that frequently so updating once in a while as we have been doing is fine IMO.

2024-03-12 18:40 UTC, paulromano commented
@MicahGale if you want to remove the draft status on this PR, I think it's ready to go.

2024-03-12 19:33 UTC, MicahGale commented
@paulromano There's still a dozen docker workflows to update. I was going to make a patch and try applying it to all docker files and see how that goes.

2024-03-13 01:40 UTC, MicahGale commented
@paulromano on next release could you remember to check for any warning logs in the deploy CI?

2024-03-13 09:33 UTC, shimwell commented
I noticed we make use of ```coverallsapp/github-action@master``` near the bottom of in the Ci.yml and this results in a node 16 warning.

perhaps this could also be updated to version 2.2.3 or simply 2

https://github.com/coverallsapp/github-action

2024-03-13 13:20 UTC, MicahGale commented
So the issue here is that coveralls has a `main` and `master` branch, and only deploys to `main`. So I think using a specific version will be more consistent.

2024-03-13 16:08 UTC, paulromano approved these changes
All looks good, including that coveralls one going to v2. Thanks!

2024-03-13 16:08 UTC, merged