Re: Issue #2939 - Implement contains for universe and geomery
openmc-dev/openmc pull request #3004
Opened 2024-05-14 21:19 UTC by caderache2014

# Description

In response to issue 2939, opened by @MicahGale, I have implemented a contains method for Universe class and Geometry class with concomitant testing

Fixes # (issue)

2939

# Checklist

- [x] I have performed a self-review of my own code
- [x] I have run [clang-format](https://docs.openmc.org/en/latest/devguide/styleguide.html#automatic-formatting) (version 15) on any C++ source files (if applicable)
- [x] I have followed the [style guidelines](https://docs.openmc.org/en/latest/devguide/styleguide.html#python) for Python source files (if applicable)
- [x] I have made corresponding changes to the documentation (if applicable)
- [x] I have added tests that prove my fix is effective or that my feature works (if applicable)

2024-05-15 12:46 UTC, MicahGale requested changes
This is a start, but the logic needs work.

Also it should "Fixes #2939"

2024-05-15 12:46 UTC, MicahGale commented on openmc/geometry.py
> +            return True
Why is `True` the default value?

2024-05-15 12:46 UTC, MicahGale commented on openmc/geometry.py
> +            return cell in self._root_universe
Also why are you accessing `_private` object directly instead of through its `@property`?

2024-05-15 12:46 UTC, MicahGale commented on openmc/universe.py
> +            return cell.id in list(self._cells.keys())
Why are you checking `cell.id` and not just `cell`? Also `list` is completely unnecessary, and will make this operation 2*O(N), instead of O(1).

2024-05-15 12:46 UTC, MicahGale commented on tests/unit_tests/model.xml
> +  </model>
Why is this file here? It doesn't look like it is in any test cases.

2024-05-15 12:46 UTC, MicahGale commented on include/openmc/version.h
> +#endif // OPENMC_VERSION_H
This is out of scope.

2024-05-15 20:36 UTC, closed without merging

2024-05-16 00:56 UTC, caderache2014 commented
Hi @MicahGale  sorry about that PR. I had been working on another branch and something got corrupted. 

I submitted a new PR 

https://github.com/openmc-dev/openmc/pull/3007

It looks likes the CI test are passing. Thoughts?

2024-05-16 22:11 UTC, MicahGale commented
I need to look at this closer. You don't need to close this PR, I think changing it to draft is fine.

2024-05-16 22:37 UTC, caderache2014 commented
Well,.... the first PR (#3004) was having all kinds of error.s. 17 out of 18 tests were failing and I could not figure out why. I tried resubmitting several times and then just closed the PR #3004. I re-based my local branch openmc-dev and resubmitted everything under the PR #3007. This one (#3007) appears to pass the CI tests.

2024-05-21 19:44 UTC, MicahGale commented
Glad you got it working in #3007. That looks pretty good. In the future running the test suite locally can make debugging a lot easier. To do this:

1. Install the openmc executable from source: https://docs.openmc.org/en/stable/quickinstall.html#installing-from-source-on-ubuntu
2. Install test dependencies: https://docs.openmc.org/en/stable/devguide/tests.html
3. Run `pytest` from inside of `tests`

I remember I had some difficulty getting the test suite running personally so there might be an extra step I missed.