Fix #2994, non-existent path causes segmentation fault when saving plot
openmc-dev/openmc pull request #3038
Opened 2024-06-16 15:29 UTC by pitkajuh

# Description

As stated in the bug report, a segmentation fault happens when trying to create a plot with non-existent path in plot.xml. This pull request fixes the issue.

Fixes #2994

# Checklist

- [X] I have performed a self-review of my own code
- [X] I have run [clang-format](https://docs.openmc.org/en/latest/devguide/styleguide.html#automatic-formatting) (version 15) on any C++ source files (if applicable)
- [ ] I have followed the [style guidelines](https://docs.openmc.org/en/latest/devguide/styleguide.html#python) for Python source files (if applicable)
- [ ] I have made corresponding changes to the documentation (if applicable)
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)

2024-06-17 18:03 UTC, pshriwise requested changes
A clear improvement. Thanks @pitkajuh! Really small suggestion here but then I think it's good to go.

2024-06-17 18:03 UTC, pshriwise commented on src/plot.cpp
> +  if (!dir_exists(dir_if_present) and dir_if_present.size() > 0) {
Performing the simple check first for short-circuit of the logical expression.

```suggestion
  if (dir_if_present.size() > 0 && !dir_exists(dir_if_present)) {
```

2024-06-17 18:44 UTC, pshriwise commented
@pitkajuh I've just added a test to ensure this works as expected. Let me know if that looks alright to you.

2024-06-17 23:20 UTC, paulromano approved these changes

2024-06-18 11:56 UTC, pshriwise approved these changes

2024-06-18 11:56 UTC, merged