Implement bounding_box operation for meshes
openmc-dev/openmc pull request #3119
Opened 2024-08-17 20:36 UTC by paulromano

# Description

This PR adds a `bounding_box()` method on the mesh classes in C++ and corresponding bindings in openmc.lib. I need this functionality for an improvement of our capability to compute material volumes within mesh elements that I'm working on.

# Checklist

- [x] I have performed a self-review of my own code
- [x] I have run [clang-format](https://docs.openmc.org/en/latest/devguide/styleguide.html#automatic-formatting) (version 15) on any C++ source files (if applicable)
- [x] I have followed the [style guidelines](https://docs.openmc.org/en/latest/devguide/styleguide.html#python) for Python source files (if applicable)
- [x] I have made corresponding changes to the documentation (if applicable)
- [x] I have added tests that prove my fix is effective or that my feature works (if applicable)

2024-08-18 16:39 UTC, pshriwise requested changes
Mainly line comments from me. Thanks @paulromano!

2024-08-18 17:39 UTC, paulromano commented on src/mesh.cpp
> +  double zmax = -INFTY;
This goes against the C++ core guidelines, [ES.10](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Res-name-one)

2024-08-18 17:39 UTC, paulromano commented on include/openmc/mesh.h
> +#include "openmc/surface.h" // for BoundingBox
Good idea -- I just implemented that

2024-08-19 04:08 UTC, pshriwise commented on src/mesh.cpp
> +  double zmax = -INFTY;
Ah I see. In the example provided in that section I can see why they recommend against it (multiple types declared in the same line, but in this case I guess I disagree as the types are all the same in this case and I find it easier to read.

What I originally wrote as a suggestion and also find easier to read was:

```c++
double xmin, ymin, zmin;
xmin = ymin = zmin = INFTY;
```

But I'd imagine that's not recommended either. Anyway, let's move on. Resolving.

2024-08-19 04:09 UTC, pshriwise approved these changes
Thanks @paulromano!

2024-08-19 04:09 UTC, merged