Kinetics parameters using Iterated Fission Probability
openmc-dev/openmc pull request #3133
Opened 2024-09-16 19:24 UTC by JoffreyDorville

# Description

Calculation of adjoint-weighted kinetics parameters (effective generation time and effective delayed neutron fraction) using the Iterated Fission Probability (IFP) method.

This implementation uses the same approach as the IFP implementation in Serpent 2 documented in [1].

To generate results for both effective generation time and effective delayed neutron fraction, IFP settings need to be set:

```
settings.iterated_fission_probability = {
    "parameter": "both",
    "n_generation": 5
}
```
and a specific tally has to be set:

```
tally = openmc.Tally(name="ifp-scores")
tally.scores = [
    "ifp-time-numerator",
    "ifp-beta-numerator",
    "ifp-denominator"
]
```

Testing is still in progress. I will update the draft to PR once I have finished the remaining tests.

# References

[1]  J. Leppänen, M. Aufiero, E. Fridman, R. Rachamin, and S. van der Marck, “Calculation of effective point kinetics parameters in the Serpent 2 Monte Carlo code,” Annals of Nuclear Energy, vol. 65, pp. 272–279, Mar. 2014, doi:10.1016/j.anucene.2013.10.032

# Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have run [clang-format](https://docs.openmc.org/en/latest/devguide/styleguide.html#automatic-formatting) (version 15) on any C++ source files (if applicable)
- [ ] I have followed the [style guidelines](https://docs.openmc.org/en/latest/devguide/styleguide.html#python) for Python source files (if applicable)
- [ ] I have made corresponding changes to the documentation (if applicable)
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)

2024-10-02 06:39 UTC, zhangzeqin1997 commented
I have tested this feature, and everything works well at the moment. I would like to inquire if there are any plans to add output for the individual delayed neutron group fractions and decay constants, similar to how it is done in MCNP.

2025-01-14 22:19 UTC, paulromano requested changes
Thanks for this PR @JoffreyDorville and apologies it's taken me some time to get you some feedback on this. Here is a set of initial comments. In addition to the line comments/questions below, I'll add two other comments:

- It would be nice if some of the logic/functionality here could be isolated into its own source file (ifp.h/ifp.cpp).
- I see quite a few blocks of code that seem repeated (for example, in bank.cpp and eigenvalue.cpp). If there's any way to encapsulate them in a function so that they don't need to be repeated, that would help reduce the total number of lines.

2025-01-14 22:19 UTC, paulromano commented on include/openmc/settings.h
> +  ifp_parameter; //!< Parameter to calculate for Iterated Fission Probability
I see right now this is determined based on user input in the `Settings` object. I think it would be better if this was determined automatically based on what scores show up in tallies (i.e., if the user specified "ifp-time-numerator" as a score, then activate the logic to collect the information needed accordingly), which leaves less for the user to think about.

2025-01-14 22:19 UTC, paulromano commented on src/physics.cpp
> +    vector<double> updated_ifp_lifetimes;
This will result in memory allocation in the middle of a particle's transport, which is never desirable 1) because it can degrade threading efficiency and 2) it doesn't fit GPU programming models well. Is there any way we can avoid the memory allocation?

2025-01-14 22:19 UTC, paulromano commented on src/particle.cpp
> +  this->lifetime() += distance / this->speed();
Given that `lifetime` looks identical to `time` here, can you explain what the difference between the two is?

2025-02-04 20:38 UTC, JoffreyDorville commented on src/particle.cpp
> +  this->lifetime() += distance / this->speed();
The main difference between time() and lifetime() is that when a particle is created via Particle::from_source, lifetime() will be reset to 0 while time() will be set to the source time. This means that time() will not necessarily be equal to 0 when Particle::from_source is called if we already did multiple batches. In my case, I really need a timer that is reset every time a particle is created.

2025-02-05 22:43 UTC, JoffreyDorville commented on include/openmc/settings.h
> +  ifp_parameter; //!< Parameter to calculate for Iterated Fission Probability
The code now detects automatically the correct value for ifp_parameter based on the user defined tallies. It also detects whether settings::ifp should be true or not. I removed the iterated_fission_probability settings so that the user only declares the number of generations via ifp_n_generation instead. If the user does not declare this value and IFP tallies are requested, the code will use a default value of 10 generations.

2025-02-11 17:28 UTC, JoffreyDorville commented on src/physics.cpp
> +    vector<double> updated_ifp_lifetimes;
With the refactoring, these vectors are only declared inside the "if (settings::ifp)" loop now. This should no longer impact the non-IFP user.

For the IFP context, I need to use vectors in the current implementation as the number of generations is only known at runtime (user input). There are options to use arrays instead with some limitations but this is not what I chose for this implementation.

2025-02-11 17:37 UTC, JoffreyDorville commented
I isolated every IFP functionality within ifp.cpp/ifp.h as suggested. The code reads definitely better now, especially in eigenvalue.cpp. There is a balance to find when encapsulating parts of the IFP code in their own functions that we can discuss. Interestingly, it ended up in more lines of code, but the readability and maintainability should be better now.

2025-03-07 21:46 UTC, realmisch commented
Hello everyone, I've done some testing with support from [@sallustius](https://github.com/sallustius) in using the IFP tallies and modifying the implementation to permit using a `DelayedGroupFilter` since the delayed group index is already calculated during transport. With this modification, I've been able to calculate the group-wise delayed fraction constants and do 6-group point kinetics solely from OpenMC results. The results have been in agreement with Serpent's IFP results for the same geometry and simulation settings.

@JoffreyDorville how would you like to proceed with adding this capability to your branch?

2025-04-03 15:02 UTC, JoffreyDorville commented
Thanks @realmisch for your contribution with the delayed group filter, I look forward to using it! I would recommend to create another PR dedicated to this filter. If you rely on this PR for testing, I would first create a draft PR and wait until this PR (#3133) is merged to promote it to PR.

@paulromano I implemented another method to avoid memory allocation at runtime which is available here: https://github.com/JoffreyDorville/openmc/tree/kinetics_ifp_mpi_optim_scalable

Both implementation can be useful depending on what the focus is for the user. With the current PR state, we focus on limiting the peak memory usage. With the branch on my fork, we focus on multi-threading scalability with the added benefit of fitting GPU programming models better in theory.

I think the difference in implementation between the two methods are limited enough so that I can propose to have both method available in OpenMC. Adding a new parameter could allow the user to choose which method to use. I can do this in this PR or in a followup PR.

Let me know what you think!

2025-04-11 21:27 UTC, paulromano approved these changes
@JoffreyDorville Thanks for the updates on this and for sharing your performance data with me. I went through this again today in detail and made a bunch of updates and simplifications. Notably, there were three functions in ifp.cpp that were all kind of the same thing, so I combined those.

There are a few loose ends but these are things we can continue to look into and if need be can submit follow-up PRs:
- The `lifetime` variable is needed because we have the `time` variable propagate through fission generations. It looks like I did deliberately make that choice when I put the time variable in originally (see 4831456144e778449c5fd54bfbeeff84caf6d7e5 from #1934), but thinking about it now it's not clear to me that it really even makes sense.
- I have some ideas about how we can better manage memory of the lifetimes / delayed groups that are stored over the latent generations, but this will take some more work.

2025-04-14 14:07 UTC, merged