Add a composite surface called vessel, which includes a 'ZCylinder' with ellipsoids on top and bottom.
openmc-dev/openmc pull request #3168
Opened 2024-10-13 18:01 UTC by nsedayilmaz

2024-10-15 17:55 UTC, pshriwise requested changes
Thanks @nsedayilmaz! This is a nice addition and great application for the composite surface. I've made a few small comments here. We'll want to add some tests for this surface as well.

2024-10-15 17:55 UTC, pshriwise commented on openmc/model/surface_composite.py
> +                """
```suggestion
        """
        General equation for an ellipsoid: 
        (x-xo)^2/r^2 + (y-yo)^2/r^2 + (z-zo)^2/h^2 = 1               
        """
```

Suggesting we reduce this comment to it's critical piece -- we cover the GQ equation in the documentation as it is.

2024-10-15 17:55 UTC, pshriwise commented on openmc/model/surface_composite.py
> +class Z_Vessel(CompositeSurface):
```suggestion
class ZVessel(CompositeSurface):
```

2024-10-15 17:55 UTC, pshriwise commented on openmc/model/surface_composite.py
> +        """
We'll want to include some parameter descriptions in the documentation string here.

2024-11-09 17:16 UTC, paulromano approved these changes
I did some refactoring on this branch to generalize it so it can be oriented in the x-, y-, or z-directions instead of just z. @pshriwise if you can take another quick look, I'll need your approval to merge. Thanks!

2024-11-09 19:42 UTC, pshriwise requested changes
Maybe a missing type hint but other than that it looks good to me!

2024-11-09 19:42 UTC, pshriwise commented on openmc/model/surface_composite.py
> +                 center: Sequence[float] = (0., 0.), axis='z', **kwargs):
Should there be a type hint for `axis` here?

2024-11-09 23:42 UTC, pshriwise approved these changes
Thanks @paulromano!

2024-11-10 00:13 UTC, nsedayilmaz commented
Thank you both for working on this request!

2024-11-12 23:11 UTC, merged